### ISSUE TITLE
Scan ID for different country

### ISSUE THREAD

**Issue by achinverma** [BlinkID/blinkid-android#1]
hi , i am using this library to perform scans of various ID cards in my  app and i have imported the demo and when i run the demo to scan this ID card image (which is given with demo)
![croid](https://cloud.githubusercontent.com/assets/2811593/10159815/42206b90-66b8-11e5-8508-36a33c7050a2.jpg)

it is working fine , 

but i want to detect ID CARDS of my country , Language is English.
and i want to  detect fields like name, fathers name, sex, age, address , date, as you can see in  the sample image below
i will post a picture of VOTER CARD of my country, you can see all the fields. 
and to detect all these fields what are things that i have change in your demo or any algorithm for this ?
![voter_card](https://cloud.githubusercontent.com/assets/2811593/10160640/73135646-66bc-11e5-86dc-7f063592f83d.JPG)

**Comment by DoDoENT** [comment]
Hi achinverma,

BlinkID can only scan documents containing [Machine Readable Zone]((https://en.wikipedia.org/wiki/Machine-readable_passport)). ID cards in your country do not adhere to MRTD standard so they cannot be scanned with BlinkID. However, I suggest trying out our other product, [BlinkOCR](https://github.com/BlinkOCR/blinkocr-android) to scan segments like Elector's name, age, etc.

**Comment by achinverma** [comment]
ok , i am closing  this thread, and i wiill post in  BlinkOCR
