### ISSUE TITLE
APP Sharing that use BlinkID

### ISSUE THREAD

**Issue by ldgbc** [BlinkID/blinkid-android#107]
It seem like BlinkID intent to be API only, they won't be really creating any APP themselves?

Anyone that create their own APP that is for usage with feature such as Saving to File or Exporting the data. Have anyone made their own app and would like to share?

BlinkID is great and all but there seem to be only two way to save the data: Add as Contact (which doesn't seem to input any data when I tried it) or Email (which is good, contain all the information it extracted but I don't want it to be email. I want save it for storage.

**Comment by culoi** [comment]
Hi @ldgbc 

This is just to showcase what our SDK is able to do. The decision of the team is to allow only share via an email client, but you can easily integrate our SDK into your app. 
Then you can process the result and share it in the whatever way you want, via email, save to storage, Bluetooth or Viber, this is entirely depending on your coding skills. 

With this option (share via email) we just want to let our users know that we have a possibility to share result via 3rd party instances. 

Regards

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
