### ISSUE TITLE
Remove brand name of Blink Id in Android application

### ISSUE THREAD

**Issue by KavyaHarisha** [BlinkID/blinkid-android#112]
![screenshot_20180718-161124](https://user-images.githubusercontent.com/27813072/42876864-9b876fa8-8aa5-11e8-9d67-6fd30df53ec2.jpg)

Please, observe the above attachment,  the rectangle box, and `Micro Blink` brand name is displaying, how to remove the brand name and rectangle box.
Could you please help me here.
Advance thanks.

**Comment by culoi** [comment]
Hello @KavyaHarisha 

Microblink overlay is part of our demo license key. It can be removed, but you have to contact us at support@microblink.com with more details about why is it required to remove overlay in the demo.

Production license key (paid license key) doesn't contain Microblink overlay.

Regards

**Comment by KavyaHarisha** [comment]
Thank you for the information.
Means your saying, for demo license key will show the Microblink overlay and not for the Production license key will show the Microblink overlay right(Android)?
But in IOS, it's not appearing the square box and MicroBlink overlay for demo licence key also.
What is the reason behind it?
Could you explain to me.

**Comment by culoi** [comment]
Hello @KavyaHarisha 

The square box is default overlay on all our BlinkID SDK's. 
Did you maybe edit overlay or create Custom UI? Do you maybe using PDF417 SDK which doesn't contain the box? 

On iOS is no Microblink logo by design. But on both platforms, we are showing Using time-limited license! warning toast when using the demo license key. 

Regards

**Comment by KavyaHarisha** [comment]
I am not using PDF417 SDK, I don't want to scan the barcode, only need to scan the driving licence.
So I am using Blink Id SDK.
Could please tell me how to remove the overlay for demo licence key and Microblink brand name for Blink Id SDK.

**Comment by culoi** [comment]
Hello @KavyaHarisha 

Sure thing, please contact us at support@microblink.com with more details about why is it required to remove overlay in the demo.

Regards

**Comment by KavyaHarisha** [comment]
There is no particular reason, In IOS without modifying the code(by using demo sample), they are not showing the Microblink overlay and square box. In the same way, is there any chance in android also without modifying the code don't show the Microblink overlay and square box.
Thank you.

**Comment by KavyaHarisha** [comment]
Thank you for the information, I understand what you saying.

At least is it possible to remove the company brand name `Micro Blink`, If
It possible, provide sample code it is very useful to me.
Or for removing `Micro Blink` I have to contact support@microblink.com by
this mail day?

Advance thanks.
