### ISSUE TITLE
Image rotating on callback

### ISSUE THREAD

**Issue by BilalMH** [BlinkID/blinkid-android#113]
I'm using the latest version of Blink. I scan the front of a UK licence (in portrait mode) but when it returns to my ImageView it is flipping the licence into Landscape. Any ideas how to fix this? 

Thanks

**Comment by BilalMH** [comment]
![screenshot_20180629-201013](https://user-images.githubusercontent.com/29797901/44022505-abd8be7c-9edf-11e8-8ce0-2e61b8904b51.jpg)
![screenshot_20180629-200957](https://user-images.githubusercontent.com/29797901/44022507-abf03110-9edf-11e8-9899-fbe2d9ae3517.jpg)


Hi @matvidako  please see attached. Thank you

**Comment by i1E** [comment]
Hi @BilalMH,

probably you have wrapped concrete recognizer with `SuccessFrameGrabberRecognizer` for obtaining success frames. `SuccessFrameGrabberRecognizer` returns whole camera frame in the native orientation of the camera device which is landscape right. If you are using the EudlRecognizer, you can obtain cropped document image by using [EudlRecognizer.Result.getFullDocumentImage](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/eudl/EudlRecognizer.Result.html#getFullDocumentImage--) which is always in correct orientation.

Also you can check [this code snippet](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/LibUtils/src/main/java/com/microblink/result/extract/RecognitionResultEntry.java#L122-L162) which shows how orientation of the successFrame can be corrected.

**Comment by BilalMH** [comment]
@i1E this has worked perfectly. Thank you very much for your help!
