### ISSUE TITLE
Animated Dots

### ISSUE THREAD

**Issue by MarishkaKravchenko** [BlinkID/blinkid-android#116]
Hey guys
My team is planning to buy license, but we have a trouble with animated dots. We want to use Fragment with custom buttons (we don't use RecognizerRunnerFragment) , so how we can enable animation dots in this case? (in current version)

**Comment by matvidako** [comment]
Hi,

you'll need to use OcrResultDotsView.
You can see how it's used in one of the sample apps [here](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-CustomCombinedSample/src/main/java/com/microblink/blinkid/CustomVerificationFlowActivity.java)

**Comment by MarishkaKravchenko** [comment]
Sorry, I don't get it..I installed your sample (BlinkID-CustomCombinedSample) but I don' see dots http://prntscr.com/kfakn1 there
I also tried to add OcrResultDotsView in my app, but nothing happened

**Comment by matvidako** [comment]
Sorry about that, it seems that we had a bug in the sample app.
I've just fixed it, you can see what was wrong [here](https://github.com/BlinkID/blinkid-android/commit/378e03ba6e0f7918081507c7419376f3da50e348)

**Comment by MarishkaKravchenko** [comment]
brilliant! thank you very much!
