### ISSUE TITLE
Document detector doesn't work with DirectApi

### ISSUE THREAD

**Issue by maestr0ua** [BlinkID/blinkid-android#117]
I'm trying to setup recognition of ID cards via DirectApi.
For tests I'm using your sample project, BlinkID-DirectApiSample.

In MenuActivity I changed:

```
// MrtdRecognizer mrtdRecognizer = new MrtdRecognizer();
DocumentDetector documentDetector = new DocumentDetector(
DocumentSpecification.createFromPreset(DocumentSpecificationPreset.DOCUMENT_SPECIFICATION_PRESET_ID1_CARD),
DocumentSpecification.createFromPreset(DocumentSpecificationPreset.DOCUMENT_SPECIFICATION_PRESET_ID2_CARD));

documentDetector.setNumStableDetectionsThreshold(3);

DetectorRecognizer recognizer = new DetectorRecognizer(documentDetector);
mRecognizerBundle = new RecognizerBundle(recognizer);
```

Tested image:
![id card](https://user-images.githubusercontent.com/11719504/43717359-f593d556-998f-11e8-85ba-08a918710e1a.jpg)

Neither Camera1Activity, nor Camera2Activity produce any results

### Environment Details

**BlinkID version: 4.0.0

**Device model: Meizu m3 note

**Device Android version: 5.1

**Device ABI (processor architecture, e.g. ARMv7): ARMv8-A

### Log file
[log.txt](https://github.com/BlinkID/blinkid-android/files/2262525/log.txt)

**Comment by culoi** [comment]
Hello @maestr0ua 

What exactly are you trying to achieve here?

This document doesn't contain a valid MRZ line. 

ISO/IEC 7501-1 defines a standard for MRZ field: https://en.wikipedia.org/wiki/Machine-readable_passport

Do you want to scan MRZ line or just grab the image of the document? 

Regards

**Comment by maestr0ua** [comment]
Hello, @culoi!
I'm just trying to detect ID document, that's all. 
The weird MRZ on the picture might be confusing a bit, but detector doesn't work with any another ID documents as well, for example
![serbianid_face_no_chip](https://user-images.githubusercontent.com/11719504/43720192-7dfc7d96-9998-11e8-9f76-b6586a56af76.gif)

**Comment by maestr0ua** [comment]
DocumentDetector + RecognizerView works great, 
but DocumentDetector + RecognizerRunner doesn't work.

I thought the problem in the rotation, but changing Orientation.ORIENTATION_LANDSCAPE_RIGHT on LANDSCAPE_RIGHT or ORIENTATION_PORTRAIT didn't give any positive results

`Image img = ImageBuilder.buildImageFromCamera1NV21Frame(data, mFrameWidth, mFrameHeight, Orientation.ORIENTATION_LANDSCAPE_RIGHT, null);`

**Comment by culoi** [comment]
Hi @maestr0ua 

Is loading image from gallery requirement or you can use the camera to capture the documents well?

If using device camera is the option then I suggest using DetectorSample: https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-DetectorSample

Best regards

**Comment by maestr0ua** [comment]
No, It's not requirement, I'm just using the picture because don't have a good sample right now.
I focus camera on those picture.

There is used RecognizerView In DetectorSample, which isn't appropriate for me. Aside from BlinkId, I'm using Google Vision and native Face detector as well. So need to work with Camera directly.

Is there any ideas why DocumentDetector doesn't work with RecognizerRunner?

**Comment by culoi** [comment]
Hello @maestr0ua 

Our DirectAPI work on the single image. 

Please consider removing or setting this property:
 
>documentDetector.setNumStableDetectionsThreshold(3); 

to 1, as it looks for the 3 stable frames for the detection.

How will process work once you set up detector? 

Regards

**Comment by maestr0ua** [comment]
Without changes. Doesn't work.

Also I checked DocumentFaceRecognizer, works fine. Strangely enough, detecting a document with a face should be more difficult than detecting just a document

**Comment by maestr0ua** [comment]
Hi @culoi!
Is there any progress on this issue?

**Comment by i1E** [comment]
Hi @maestr0ua,

additional configuration is required for `DetectorRecognizer`, in BlinkID-DetectorSample it is done inside [`DetectorActivity`](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-DetectorSample/src/main/java/com/microblink/blinkid/DetectorActivity.java), you can check [these lines](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-DetectorSample/src/main/java/com/microblink/blinkid/DetectorActivity.java#L124-L146) for an example.

**Comment by maestr0ua** [comment]
@culoi yes, that's exactly what I need! Works perfectly!

Many thanks! )
