### ISSUE TITLE
Font Size Issue

### ISSUE THREAD

**Issue by leeyikkong** [BlinkID/blinkid-android#12]
The font size of the words too small will effect the result of scanning? If yes, is there have any solution to solve it?

**Comment by DoDoENT** [comment]
Hi, if physical text on card is very small, try increasing dewarp height of the decoding info which targets this text. Larger dewarp height will create larger image from this location which will have larger text.

**Comment by leeyikkong** [comment]
ok.. seems like got some improvement for my scanning result. will keep try to adjust until get the best result.
