### ISSUE TITLE
Custom UI for USDL comined 

### ISSUE THREAD

**Issue by dhruvi1kosmos** [BlinkID/blinkid-android#123]
How can i add custom UI in my fragment  for USDL combined scan? I need to add custom back button icon  and custom Torch icon

**Comment by matvidako** [comment]
Hi,

to change the torch icon use `setTorchOnIconResourceID` and `setTorchOfIconResourceID` methods in `DocumentVerificationUISettings`.

Back button is currently not supported for `DocumentVerificationUISettings`. 
Can you handle back button in your activity?
