### ISSUE TITLE
UsdlRecognizer getField marked as @NonNull

### ISSUE THREAD

**Issue by JonasPrap** [BlinkID/blinkid-android#125]
### Description

Small issue: UsdlRecognizer getField method is marked as returning @NonNull. However in documentation it is said that "required information (if it exists), or null if it does not".

So my understanding is that annotation is incorrect.

**BlinkID version:** 4.2.0

**Comment by i1E** [comment]
Hi @JonasPrap,

thank you for the report. 

Actually, the annotation is correct, but the documentation of the method isn't. This method returns parsed field if it exists, or empty String otherwise. We will fix that for the next release.
