### ISSUE TITLE
Usdl recognizer might be parsing first name wrong

### ISSUE THREAD

**Issue by JonasPrap** [BlinkID/blinkid-android#126]
### Description

http://www.coet.es/web/images/Categorias/DOCUMENTOSCOPIA/Documentos/Specimens/America_Norte/Coet_Documentos_Internacional_PEIIDDL.pdf

Scanning this barcode with UsdlRecognizer gives firstname as:
"����������������FRANￇOIS"

Issue is not noticed on iOS. It seems to give correct letter - Instead of "ￇ" a sort of "C" is shown.

### Environment Details

**BlinkID version:** 4.2.0

**Comment by i1E** [comment]
Hi @JonasPrap,

thank you for the issue report. There is a problem with the encoding of this concrete barcode. We will add support for such non standard barcodes in the next release.
