### ISSUE TITLE
fetch face Image form usdl combined reconizer

### ISSUE THREAD

**Issue by ghost** [BlinkID/blinkid-android#127]
private void buildUsdlCombinedElement() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                UsdlCombinedRecognizer usdlCombined = new UsdlCombinedRecognizer();
                usdlCombined.setReturnFaceImage(true);
//                ImageSettings.enableAllImages(usdlCombined);
                combinedRecognitionAction(usdlCombined);
            }
        }).start();
    }

    /**
     * Starts {@link com.microblink.activity.DocumentVerificationActivity} with given recognizer.
     *
     * @param combinedRecognizer recognizer that will be used.
     */
    private void combinedRecognitionAction(Recognizer combinedRecognizer) {
        DocumentVerificationUISettings uiSettings = new DocumentVerificationUISettings(new RecognizerBundle(combinedRecognizer));
        uiSettings.setBeepSoundResourceID(R.raw.beep);

        ActivityRunner.startActivityForResult(this, MY_BLINKID_REQUEST_CODE, uiSettings);
    }

 

  final UsdlCombinedRecognizer.Result recognizer = (UsdlCombinedRecognizer.Result) r.getResult();
recognizer getFaceImage()  RETURNS ""

**Comment by i1E** [comment]
Hi @dhruvi1kosmos,

from the attached code snippets it is not possible to figure out where is the problem in the integration. Please check our [BlinkID-aMinimalSample](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-aMinimalSample/src/main/java/com/microblink/blinkid/MainActivity.java) just replace `MrtdRecognizer` with `UsdlCombinedRecognizer` and `DocumentUISettings` with `DocumentVerificationUISettings`. When scan activity is done, it is important to [load scan results from intent](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-aMinimalSample/src/main/java/com/microblink/blinkid/MainActivity.java#L64).

**Comment by i1E** [comment]
Hello @dhruvi1kosmos,

Hope everything works fine now. If you still have any issues or questions, please let us know.
You can also contact us directly at support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello @dhruvi1kosmos

As this issue is inactive, we will close it. For any questions, feel free to contact us here or directly at support@microblink.com
We would be more than happy to help.

Best regards.
