### ISSUE TITLE
FR: setFirstSideInstructions instead of setFirstSideInstructionsResourceID

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-android#129]
### Description

Currently, for setting custom instructions and splashscreen text, we have to use methods like `setFirstSideInstructionsResourceID(rid)`. Is it possible to support `setFirstSideInstructions(instructionsString)`, `setSecondSideInstructions(instructionsString)`, etc? We're consuming this SDK via your react native module, and this would allow us to support languages that BlinkID doesn't support yet, as well as use our own custom phrasings. Thanks!

### Additional information

this [pull request](https://github.com/BlinkID/blinkid-react-native/pull/77) adds support for customizable text to your react native module, and works on iOS but not Android due to this issue

**Comment by i1E** [comment]
Hi @mvayngrib,

we added options that you have requested in the v4.4.0, also we exposed them to API of the react-native wrapper.
