### ISSUE TITLE
Colombia National ID Back is not working ColombiaIdBackRecognizer?

### ISSUE THREAD

**Issue by kiritm-nimblechapps** [BlinkID/blinkid-android#130]
Hi,

I Want to scan the Colombia National ID Card, The card have both side of the data, I Scan the front using **ColombiaIdFrontRecognizer** it's working fine and getting data of front. But at back side Use ColombiaIdBackRecognizer, There is not scanning process and nothing get results. Please help me how to scan the back part of Colombia.

**BACK**

![screen shot 2018-10-10 at 12 30 20 pm](https://user-images.githubusercontent.com/17870723/46718245-43358680-cc88-11e8-8cc2-f3f9c55642b9.png)

**==================================================================**

**FRONT**

![screen shot 2018-10-10 at 12 30 15 pm](https://user-images.githubusercontent.com/17870723/46718232-3add4b80-cc88-11e8-95af-650ae807b64d.png)

**Comment by i1E** [comment]
Hi @kiritnim,

this is fake ID card and probably the barcode does not have a valid format. Please try to scan real documents. If you have problems on real documents, please contact us on support@microblink.com.

**Comment by kiritnim** [comment]
> Hi @kiritnim,
> 
> this is fake ID card and probably the barcode does not have a valid format. Please try to scan real documents. If you have problems on real documents, please contact us on [support@microblink.com](mailto:support@microblink.com).

Yes. This is fake then why it scanning of front.

**Comment by i1E** [comment]
Because the front side is well formatted. For the back side, the watermark "i" over the barcode is also problematic.

**Comment by kiritnim** [comment]
Okay, Thanks.

**Comment by kiritnim** [comment]
> Because the front side is well formatted. For the back side, the watermark "i" over the barcode is also problematic.

Okay Thanks. I have

**Comment by andresmtz98** [comment]
Same issue here :/, please reopen it

**Comment by culoi** [comment]
Hi,

Please try to use our latest BlinkID Demo app: https://play.google.com/store/apps/details?id=com.microblink.blinkidapp&hl=en_US

Sometimes the problem can be in the barcode as Colombia ID card barcode is quite dense, so there can be numerous things that can cause the barcode as unreadable. 

Also, please let us know on how many real samples did you test (was this a physical card, scanned sample, or image from the internet) and if possible, please contact us with more details to support@microblink.com

Regards

**Comment by Brankacro** [comment]
Hello,

As this is inactive we are closing it. In case of any questions, please reopen it or contact us directly at support@microblink.com
We will be more than glad to help.
Best regards.
