### ISSUE TITLE
How can we make Recognizer view to default portrait. 

### ISSUE THREAD

**Issue by KavyaHarisha** [BlinkID/blinkid-android#132]
I commented on below issue, but I do not receive any response that comment, so create a new issue and that issue link was `https://github.com/BlinkID/blinkid-android/issues/93`.

Hi,
Could you please help me, how to set Portrait mode of scanning activity. Please find my below code.

EudlRecognizer mRecognizer = new EudlRecognizer();
RecognizerBundle mRecognizerBundle = new RecognizerBundle(mRecognizer);
DocumentUISettings settings = new DocumentUISettings(mRecognizerBundle);
ActivityRunner.startActivityForResult(this, MY_REQUEST_CODE, settings);

I am using the above code for scanning the driver license of UK.
Here my problem was when scanning the driving license, the activity rotates in Landscape and Portrait mode. But my requirement was, it should be in Portrait mode always.
How can I achieve it?

Advance thanks.

**Comment by i1E** [comment]
Hi @KavyaHarisha,

currently it is not possible to force the DocumentScanActivity to landscape mode. To achieve this, you can [embed RecognizerRunnerView into yourt custom scan activity](https://github.com/BlinkID/blinkid-android#recognizerRunnerView). In this way you will have more control over the UI of your scan activity and will be able to use [RecognizerRunnerView.setInitialOrientation](https://blinkid.github.io/blinkid-android/com/microblink/view/CameraViewGroup.html#setInitialOrientation-com.microblink.hardware.orientation.Orientation-) and [RecognizerRunnerView.setOrientationAllowedListener](https://blinkid.github.io/blinkid-android/com/microblink/view/BaseCameraView.html#setOrientationAllowedListener-com.microblink.view.OrientationAllowedListener-) to force the landscape orientation.

**Comment by KavyaHarisha** [comment]
Thank you for the information.
I will look into it.
