### ISSUE TITLE
How to trigger recognition event in a RecognizerRunnerView object when setPhotoMode(true)

### ISSUE THREAD

**Issue by VicEsquivel** [BlinkID/blinkid-android#134]
### Given: 
```java
RecognizerRunnerView mRecognizerRunnerView = new RecognizerRunnerView(this);
mRecognizerRunnerView.setPhotoMode(true);
mRecognizerRunnerView.create();
```

**1.** How exactly can I get to trigger the `recognition` event in the `mRecognizerRunnerView` when it has the `setPhotoMode(true)`?
 
**2.** How should I call the `takePicture` event or alike so that the `mRecognizerRunnerView` receives correctly the picture in an `onPictureTaken` and start processing it?

### Use case:
When I launch a custom RecognizerRunnerView for a custom document, and it elapses more than N seconds without processing it, we give the user the alternative to take the picture and store it to continue the flow, and trying to execute the recognition on a taken picture in a second step, rather than  waiting too long for the realtime recognition to actually recognize the document using the `video camera manager`, and use the `Photo camera manager` instead.

### Documentation used as reference
[com.microblink.view.recognition.RecognizerRunnerView](https://blinkid.github.io/blinkid-android/com/microblink/view/recognition/RecognizerRunnerView.html)
[com.microblink.view.BaseCameraView.setPhotoMode](https://blinkid.github.io/blinkid-android/com/microblink/view/BaseCameraView.html#setPhotoMode-boolean-).

**Comment by matvidako** [comment]
Hi Victor,

setPhotoMode() is what remains of the old API and it currently doesn't do anything useful.

You can implement your use case by using direct API instead, you can start by looking at the [sample app](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-DirectApiSample).

**Comment by matvidako** [comment]
Hi Victor,

in case you missed it, you can now do this using the new high res image capture added in [v4.5](https://github.com/BlinkID/blinkid-android/releases/tag/v4.5.0).

**Comment by Brankacro** [comment]
Hello Victor,

As this is inactive, we are closing it. In case of any questions, feel free to reopen it, or contact us directly at support@microblink.com
We will be more than glad to help.
Best regards.
