### ISSUE TITLE
Date format has additional trailing dot at the end

### ISSUE THREAD

**Issue by ArmanIzad** [BlinkID/blinkid-android#137]
Hi,

I'm using blinkId version 4.4.0. 

I noticed for the recognizers that I am using (MyTentera, MRTD, IKad), the date always have a trailing dot at the end: 19.01.1994. or 14.06.2019. 

MyTentera: 
![image](https://user-images.githubusercontent.com/11865348/49349069-dcf73e00-f6e3-11e8-829e-c474f73e18ab.png)

MRTD: 
![image](https://user-images.githubusercontent.com/11865348/49349077-e41e4c00-f6e3-11e8-9790-20e2ce9936b9.png)

IKad:
![image](https://user-images.githubusercontent.com/11865348/49349081-eaacc380-f6e3-11e8-9ed0-13235d92bdc2.png)

For MyTentera and MRTD I could use the stringResult/originalDateString, but for IKad it can only return the Date object, hence I would need to either preprocess the date to remove the trailing dot at the end, or reconstruct the date using day/month/year which is not ideal. 

Any chance to get this fixed? Thanks.

**Comment by i1E** [comment]
Hi @ArmanIzad,

SDK returns [com.microblink.results.date.Date](https://blinkid.github.io/blinkid-android/com/microblink/results/date/Date.html) object which stores day, month and year as separate members. Date class provides getters for them.

In the debugger, IDE uses Date.toString() to show you the representation of the Date object, and toString method is implemented to show date in the format that you see.

**Comment by ArmanIzad** [comment]
> Hi @ArmanIzad,
> 
> SDK returns [com.microblink.results.date.Date](https://blinkid.github.io/blinkid-android/com/microblink/results/date/Date.html) object which stores day, month and year as separate members. Date class provides getters for them.
> 
> In the debugger, IDE uses Date.toString() to show you the representation of the Date object, and toString method is implemented to show date in the format that you see.

Thanks for the reply. Why does the Date.toString() returns additional dot at the end? i.e: "19.01.1994." instead of "19.01.1994"?
```java
@NonNull
    public String toString() {
        return String.format(Locale.US, "%02d.%02d.%d.", this.lIIIllIIlI, this.IIIIIllIll, this.IIIIIlIIII);
    }
```
My use case is I want to reformat the date: "19.01.1994" to something else, say "1994-01-19", but with the additional dot I can't use the Date.toString().

**Comment by i1E** [comment]
Hi @ArmanIzad,

then don't use Date.toString(), use Date.getDay(), Date.getMonth() and Date.getYear() and format date as you wish.

**Comment by ArmanIzad** [comment]
ok sure thanks
