### ISSUE TITLE
High Res Frame Issue

### ISSUE THREAD

**Issue by Stockholmm** [BlinkID/blinkid-android#139]
Hi team, 

I've been trying to use high res frame capture but the result is actually lower quality than the cropped, dewarped image obtained from detector recognizer. It also appears that high res frame capture produces lower quality results than system screenshot too. Weird behavior? 

I'm also having trouble extracting cropped, dewarped image of card when bundling Detector.Recognizer and PDF417.Recognizer. Feels like I'm doing something fundamentally wrong. 

Thanks,

![blink - copy](https://user-images.githubusercontent.com/46700729/51159648-4bd5c400-1858-11e9-8ccb-ab9f24e861fd.jpg)i

Edit: These pics in attachment are original pixel sizing.

**Comment by matvidako** [comment]
Hi,

enabling high res frames with enableHighResSuccessFrameCapture(true) won't simply replace images with high res ones, there is a completely different way to get them, to see how to do it check the [images sample](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java).

And to see how to get the image from detector recognizer check the [detector sample](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-DetectorSample/src/main/java/com/microblink/blinkid/DetectorActivity.java).

**Comment by Brankacro** [comment]
Hello @Stockholmm,

We are closing this, as it is inactive. In case of any questions, feel free to contact us. Also, you can always contact us directly at support@microblink.com
Best regards.
