### ISSUE TITLE
Customize Card Size

### ISSUE THREAD

**Issue by leeyikkong** [BlinkID/blinkid-android#14]
Can we customize our own card size? bigger / smaller than standard card size.
Thank You.

**Comment by i1E** [comment]
Hi @leeyikkong,

yes, you can customise the card size as stated [here](https://github.com/BlinkID/blinkid-android#defining-how-document-should-be-detected) if you use our [templating API](https://github.com/BlinkID/blinkid-android#-scanning-templated-documents-with-blinkocr-recognizer). If you are using BlinkOCR recognizer, you have to set [DetectorSettings](https://blinkid.github.io/blinkid-android/com/microblink/detectors/DetectorSettings.html) on [BlinkOCRRecognizerSettings](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkocr/BlinkOCRRecognizerSettings.html) by using method [setDetectorSettings](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkocr/BlinkOCRRecognizerSettings.html#setDetectorSettings-com.microblink.detectors.DetectorSettings-). You have to [define your DocumentDetectorSettings](https://github.com/BlinkID/blinkid-android#setting-up-of-document-detector) and to detect card with custom size,  define its aspect ratio (width/height) by passing desired [DocumentSpecification](https://blinkid.github.io/blinkid-android/com/microblink/detectors/document/DocumentSpecification.html) to **DocumentDetectorSettings** constructor. 

The following code snippet can help you:
```java
BlinkOCRRecognizerSettings settings = new BlinkOCRRecognizerSettings();
...
// use preset for ID card, but change the aspect ratio
DocumentSpecification idSpec = DocumentSpecification.createFromPreset(
                DocumentSpecificationPreset.DOCUMENT_SPECIFICATION_PRESET_ID1_CARD);
// set custom aspect ratio (width/height) for your document
idSpec.setAspectRatio(1.843);
// set your decoding infos (locations of fields of interest from the document, represented by rectangle defining the position of interest relative to detection)
idSpec.setDecodingInfos(decodingInfos);
DocumentDetectorSettings detectorSettings = new DocumentDetectorSettings(
                new DocumentSpecification[]{idSpec});
// set the number of subsequent close detections must occur before treating document detection as stable
detectorSettings.setNumStableDetectionsThreshold(3);
settings.setDetectorSettings(detectorSettings);
...
```

**Comment by leeyikkong** [comment]
i already recalculate all the position of the information i want to get from the card and idSpec.setAspectRatio() already use the width / the height of the card. But its seems like did not work. the calculation park need to use the current card size to calculate right? thank you

**Comment by leeyikkong** [comment]
i know whats the problem already. idSpec.setAspectRation(1.843f). thanks
