### ISSUE TITLE
High-res screen capture crashes

### ISSUE THREAD

**Issue by DanielProtopopov** [BlinkID/blinkid-android#143]
I'm trying to take a high-res screenshot with the example code:

 mRecognizerView.captureHighResImage(new HighResImageListener() {
                            @Override
                            public void onHighResImageAvailable(@NonNull HighResImageWrapper highResImageWrapper) {
                                Image image = highResImageWrapper.getImage();
            MediaStore.Images.Media.insertImage(getContentResolver(), image.convertToBitmap(), "Image", "Description");
                            }
                        });

And for some reason sometimes the application crashes saying that camera is no longer available (it becomes null). This steps from the fact that I'm taking the screenshot from the OnScanningDone, after which the application exits. Is there a way to wait until the listener finishes within the same thread or avoid it running in a separate thread?

**Comment by matvidako** [comment]
Hi,

capturing high res frame doesn't take that long, so you can just stay on your scan screen until it's done. Our default scan activities do exactly that.
in `onScanningDone`
1. pause scanning
2. call capture high res frame
3. in `onHighResImageAvailable` scanning is really done, so now you can exit scan screen
