### ISSUE TITLE
High res image rotated

### ISSUE THREAD

**Issue by Jameido** [BlinkID/blinkid-android#145]
### Description

I allow the users to manually take a picture when the document can't be recognised, for example isn't a supported document type like the Italian ID card in paper format. 

To do this I'm using 

```
    private void takePhoto() {
        showLoadingDialog();
        mRecognizerView.captureHighResImage(this);
        mRecognizerView.pauseScanning();
    }
```

And listening for the callback with:

```
    @Override
    public void onHighResImageAvailable(@NonNull HighResImageWrapper highResImageWrapper) {
        highResImageWrapper.getImage().convertToBitmap();
        highResImageWrapper.getImage().getImageOrientation(); //ORIENTATION_PORTRAIT_UPSIDE 
    }
```

But the resulting bitmap is always rotated by 90°, I would like to know how to get the image with the correct orientation or how many degrees I should rotate the bitmap to achieve it. I know this rotation is device dependent.

I already tried saving it to a file with the code below and extract the rotation from the EXIF but it didn't help, the value is always ORIENTATION_UNDEFINED.

```
    @Override
    public void onHighResImageAvailable(@NonNull HighResImageWrapper highResImageWrapper) {

            String imagesFolderPath = createImagesFolder();
            String imagePath = imagesFolderPath + "/highRes.jpg";
            
            File vFile = new File(imagePath);
                
            highResImageWrapper.saveToFile(vFile);

            ExifInterface exif = new ExifInterface(imagePath);
            int rotation = exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL); //ORIENTATION_UNDEFINED
    }
```

### Environment Details

**BlinkID version:** 4.6.0

**Device model:** Nexus 5X

**Device Android version:** 8.1.0

**Device ABI (processor architecture, e.g. ARMv7):** ARMv8-A 

### Log file

[blinkid_log.txt](https://github.com/BlinkID/blinkid-android/files/2859392/blinkid_log.txt)

### Additional information

This is an example of the resulting bitmap
<img width="844" alt="screenshot 2019-02-13 at 09 06 20" src="https://user-images.githubusercontent.com/6197669/52697258-5c6d7d00-2f71-11e9-8454-a6bf81ff1f9d.png">

**Comment by matvidako** [comment]
Hi,

image orientation that we return is the orientation of the device when the image was taken, but adjusted on devices with flipped camera.
Nexus 5X is one of the devices with flipped camera, so if you take the image in landscape right, we'll adjust image orientation to ORIENTATION_LANDSCAPE_LEFT.

So you'll need to rotate the bitmap like this:
ORIENTATION_LANDSCAPE_LEFT -> 180
ORIENTATION_PORTRAIT -> 90
ORIENTATION_PORTRAIT_UPSIDE -> -90

**Comment by Jameido** [comment]
Hi and thank you for the fast and clear answer, I'll use the sensor orientation to know if the phone is one of the ones with "flipped" camera.
