### ISSUE TITLE
Mykad not working, also on the sample app, version 4.7

### ISSUE THREAD

**Issue by damienlo** [BlinkID/blinkid-android#150]
Hello,

I recently upgraded blinkID to the version 4.7
Unfortunately Mykad recognizer is not working anymore. 
This is also the case when using the blink sample app.
 Cf video

---

### Description

https://vimeo.com/325621259

### Environment Details

**BlinkID version:** 4.7

**Device model:** S8

**Device Android version:** 9.0

**Comment by matvidako** [comment]
Hi Damien,

changes in recent versions made MyKad scanning much more accurate but it does take longer to scan. Plus, it's harder to scan from a screen than from an actual ID card.

Have you tried scanning printed ID examples?

**Comment by damienlo** [comment]
I just tried. So I managed to get it scanned from a paper print.
But the performance are quite bad, it takes about 30/35 seconds to get it recognized.

**Comment by matvidako** [comment]
It definitely shouldn't take that long.
We'll investigate.

**Comment by matvidako** [comment]
Hi Damien,

the problem is that you're scanning fake samples.
These usually work fine but in some cases by optimising for scanning real documents we'll make fakes much harder to scan.

If you don't have any real documents available to try, we can help, just contact us at support@microblink.com.
