### ISSUE TITLE
[4.8] US State ID available fields regression 

### ISSUE THREAD

**Issue by damienlo** [BlinkID/blinkid-android#155]
Hello,

### Description

I was going through the 4.8 release note
One particular detail caught my attention

> deprecated the following methods in UsdlRecognizer.Result and UsdlCombinedRecognizer.Result: (they have been replaced with new getters):

The list of new getter is making sense, the API becomes more consistent.
But how should I proceed to get my hands of the following informations, now that getFields is deprecated
- IssuerIdentificationNumber
- AKAGivenName
- AKAMiddleName
- AKAFamilyName

And addresses related fields such as
- PostalCode
- AddressPostalCode
- AddressCity
- [...]

### Environment Details

**BlinkID version:**
4.8

**Comment by matvidako** [comment]
Hi Damien,

although `getField` has been deprecated we won't be removing it until we make sure that we're providing getters for all _useful_ fields.

It would be helpful if you could share more info about your use case and why you'd need those fields.

**Comment by damienlo** [comment]
Hi matvidako,

Regarding `IssuerIdentificationNumber` it is **needed** to know which authority (AAMVA or ARISTOTLE) we need to contact to make sure the Driving licence is a valid one. 

On the subject of validation, diminutives are very common in the USA. 
AKAGivenName/AKAMiddleName/AKAFamilyName are then necessary to do some matching.
Let's take for instance someone named Robert Smith. He might decide to be called Bob Smith or Rob Smith. Then he might use of one oftheses names for his address, simply because he can.
Theses fields could be the link between someone identity and another document or an address.

Also regarding address a breakdown is neat, why would we decide to remove an information that is available? A full address is less usable than Street/City/Postal Code, once again it would help decide which authority to contact to make sure the address is still valid.

**Comment by matvidako** [comment]
Thanks! We'll keep that in mind.

**Comment by damienlo** [comment]
Hello,

I recently upgraded to the version 4.9.1 and I notice that the USDL fields listed above are still deprecated.And their equivalent are not available in the UsdlRecognizer.Result.

Could we please have an update on this?

**Comment by i1E** [comment]
Hi @damienlo, you can continue to use [UsdlRecongizer.Result.getField](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkbarcode/usdl/UsdlRecognizer.Result.html#getField-com.microblink.entities.recognizers.blinkbarcode.usdl.UsdlKeys-) method, it still works like before. From the next SDK release it won't be deprecated anymore.

**Comment by Brankacro** [comment]
Hello @damienlo,

Please let us know if you still have any issues or questions. Also, feel free to contact us directly at support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello @damienlo 

As this issue is inactive, we will close it. In case of any questions or additional assistance, please let us know. We would be more than happy to help.

Best regards.
