### ISSUE TITLE
Cannot resolve Microblink maven repository, after publishing SDK with BlinkId

### ISSUE THREAD

**Issue by AndriiKarpenko** [BlinkID/blinkid-android#156]
Hello, guys! Hope you are doing well!
We are making an SDK, which is using BlinkID. For distributing our SDK we are using GitHub as maven repository (actually, it doesn't matter Github or GitLab, or something else).

All our dependencies are described in POM.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>

  <groupId>***</groupId>
  <artifactId>***</artifactId>
  <version>***</version>
  <packaging>aar</packaging>

  <dependencies>
    ....
    <dependency>
      <groupId>com.microblink</groupId>
      <artifactId>blinkid</artifactId>
      <version>4.8.0</version>
      <type>aar</type>
      <scope>runtime</scope>
    </dependency>
  </dependencies>

  <repositories>
    <repository>
      <id>MicroblinkRepo</id>
      <url>https://maven.microblink.com</url>
    </repository>
  </repositories>
</project>
```
For generating pom.xml we are using 
```
digital.wup.android-maven-publish
```

But for some reason, after adding our SDK to some application, Gradle doesn't see Microblink repository and crashes with error

```
> Could not resolve all task dependencies for configuration ':app:releaseRuntimeClasspath'.
       > Could not find com.microblink:blinkid:4.8.0.
```

Adding the repository  manually resolves the problem:
```
repositories {
   ...
   maven { url 'https://maven.microblink.com' }
}
```
But it looks weird and annoying a little bit (strange to see, that SDK cannot resolve its own dependencies and asks about it application).

I know that this is not your problem directly, but you may have faced something similar. 
Do you have any idea, why Microblink repository isn't taken from pom.xml and have to be added manually? 
Thanks for helping!

P.s. All another dependencies are resolved correctly.

**Comment by i1E** [comment]
Hi @AndriiKarpenko 

it seems that Gradle resolves repositories only if you add them manually - https://stackoverflow.com/questions/24215991/gradle-getting-list-of-maven-repositories-from-downloaded-pom.

Probably, other artifacts which are successfully resolved are from repositories listed in build.gradle.
