### ISSUE TITLE
Question. Back side of an Europe driving license.

### ISSUE THREAD

**Issue by astelmakh** [BlinkID/blinkid-android#162]
EudlRecognizer scans only the front side of a driving license. 
How can we obtain a back side (without any recognized data, only image)?

Thanks a lot.

**Comment by culoi** [comment]
Hi @astelmakh 

The easiest way to achieve this is to have 2 buttons, one for the front side (EUDLRecognizer set to .unitedkingdom) and second button with detectorRecognizer. 

You can take a look at our [detectorSample](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-DetectorSample) and check how we configure detectorRecognizer for the IDCard type of the document. 

Regards,
