### ISSUE TITLE
USDL no field for Issuing Jurisdiction Name, Issuer Identification Number and Document Discriminator

### ISSUE THREAD

**Issue by MOhsain** [BlinkID/blinkid-android#164]
i'm using this code for scanning Canada Driver License but i can not get full data from USDL

UsdlRecognizer usdl = new UsdlRecognizer();
scanAction(new DocumentUISettings(prepareRecognizerBundle(usdl)));

Please Reply.....

**Comment by matvidako** [comment]
Resolved by Microblink support

**Comment by MOhsain** [comment]
> Resolved by Microblink support

i Resolved it :)
