### ISSUE TITLE
United Arab Emirates ID Scan reading full name issue

### ISSUE THREAD

**Issue by rajubhusani** [BlinkID/blinkid-android#166]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description
Team,

We had an issue with the EID scan reading full name from the Emirates Card for a specific card holder. User actual name is "Mohammed Saim Fattah" and the scan returning the "Mohammed Salm Fattah". So in the name "Saim", SDK returning "l" instead of i. It is happening for both Android SDK and iOS SDK.

Can you please check and update us.
Note: This is happening only for this specific user ID.
Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:** : V4.9.1

**Device model:**: Any Device

**Device Android version:** : 

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by i1E** [comment]
Hi @rajubhusani,

OCR cannot be 100% accurate, but we are constantly improving our technology and machine learning based OCR.
 
If you take a closer look at these letters, difference is only in few pixels, and errors of this kind are very hard to correct. Also scanning depends on the light conditions and quality of the input image (device camera). We suggest you to present the results to the user and make them available for editing before taking the next step.

**Comment by rajubhusani** [comment]
Thanks for the clarification. I'm closing the issue.
