### ISSUE TITLE
Re scan Image and data mismatch

### ISSUE THREAD

**Issue by saifkamaal** [BlinkID/blinkid-android#169]
### Description
In middle East[UAE] we have emirates-ID which we are scanning on both sides using micro blink to get details of that.
We have observed that If we rescan the ID most of the times(not always) the data extracted from the picture is correct and Image is of previous scan.

### Environment Details

**BlinkID version: '3.18.0'

**Device model:All devices.Observed in both Android and IOS devices

**Device Android version:All versions

**Comment by matvidako** [comment]
Hi,

Can you reproduce this issue using our sample apps?

Have you considered updating to newest BlinkID version?

**Comment by rajubhusani** [comment]
Hi,

Please clear the ImageStorage every time before launching the scan page. This will ensure that you will always get the latest captured image. Otherwise you will get the Cached image.

**Comment by saifkamaal** [comment]
Hi,

Can you provide me some pointers of clearing the storage?

**Comment by rajubhusani** [comment]
Hi,

ImageStorage.clearImages() method will clear the previously scanned images from the cache. Where ImageStorage is the class that you can get the Image of the scanned page.

**Comment by matvidako** [comment]
Hi,

ImageStorage that @rajubhusani mentioned is part of the [BlinkID-UI](https://github.com/BlinkID/blinkid-ui-android) and not BlinkID SDK itself.
BlinkID UI doesn't even support the SDK version you're using, so your issue must be something else. 

Can you reproduce it with our sample apps?

**Comment by Brankacro** [comment]
Hello,

Please let us know if you are having any issues. We will be glad to help.
You can always contact us directly at support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello,

As this issue is inactive, we will close it.
For any questions you may have, feel free to contact us. Do not hesitate to contact us directly at support@microblink.com We are always glad to help.

Best regards,

Branka
