### ISSUE TITLE
One Plus7 Pro Camera Popping up while launching the app 

### ISSUE THREAD

**Issue by rajubhusani** [BlinkID/blinkid-android#170]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description
Team,

We are seeing an issue in One Plus 7 Pro device front camera Popping up, while launching our application which is integrated the BlinkID SDK & UI library. It is happening some times when kill the app from background and try to launch again. This is so weird to see that Camera coming and going for a moment. 
Can you check this out at your end as well what are the permissions and access on the Camera feature. 
Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:**
4.10.0

**Device model:** 
OnePlus 7 Pro

**Device Android version:**
9.x

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by matvidako** [comment]
Hi,

can you list the exact steps to reproduce this?

I've tried to repro it by both dismissing the app in task manager then starting the app again, and by enabling "don't keep activities" developer setting and still can't get it to happen with BlinkID UI sample app.

**Comment by rajubhusani** [comment]
Hi,
We are also not sure of reproducing this issue as this is not happening every time. If it happens one time then it is continuously reproducible. Yesterday we found and we tried to re-install the  application then it stops coming. This is so weird and unable to catch the exact flow.

**Comment by rajubhusani** [comment]
Hi,

Any luck on this? Are you guys having any attributes in Manifest about the Camera Auto focus?

**Comment by matvidako** [comment]
Hi,

I've been using OnePlus 7 Pro as my dev device for days now and still haven't been able to reproduce this.

BlinkID SDK includes `uses-feature` `android.hardware.camera.autofocus` with `required` set to `false`, while our BlinkID demo app has it set to `true`. 
Is there a known issue with this on OnePlus 7 Pro?

Can you reproduce this with one of our apps or just with your app?

**Comment by Brankacro** [comment]
Hello @rajubhusani,

Please let us know if we can be of any help. Also, you can always contact us directly at support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello @rajubhusani 

As this issue is inactive, we will close it. In case of any questions or doubts, please let us know.
Also, do not hesitate to contact us directly at support@microblink.com We will gladly assist you.

Best regards,
Branka
