### ISSUE TITLE
reading MRZ of UAE emirates ID and passport

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-android#173]
Hi Team,

We are using Blink ID 4.8.0.1 for reading MRZ of UAE emirates ID and passport.
I need to read full document image for both emirates ID and passport.
Can you please help me with the sample code.

Thanks,
Phani

**Comment by i1E** [comment]
Hi @phanikumar560,

you can find source code in our [BlinkID_AllRecognizersSample app](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID_AllRecognizersSample). You first have to [enable returning of full document images](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID_AllRecognizersSample/src/main/java/com/microblink/blinkid/MenuActivity.java#L892) on the used recognizers. When results are returned, you will be able to [obtain images](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/LibUtils/src/main/java/com/microblink/result/extract/blinkid/BlinkIDExtractionUtils.java#L46) from the recognizer result.

Also there is another [BlinkID-ImagesSample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java) which shows how to scan documents with the MRZ by using the MrtdRecognizer and store the document images on the device.

For scanning the front and back side of the UAE ID, you should use [these](https://github.com/BlinkID/blinkid-android#-united-arab-emirates-id-front-and-back-side-recognizers) recognizers. For scanning the passport, you should use the [PassportRecognizer](https://github.com/BlinkID/blinkid-android#-passport-recognizer) which is available in the latest version of the SDK (v4.11.0), so please use the latest version.

**Comment by phanikumar560** [comment]
Thanks a lot for the support.I am facing the below issue with UAE ID
In the method
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
uaeBackRecognizerBundle.loadFromIntent(data);
}
App is getting crash at this point for UAE ID.It is working fine for  mRecognizerBundle.loadFromIntent(data); // this is for passport.
Could you please help me out.
If possible please provide me sample...code for UAE ID front and back.


Thanks
Phani

**Comment by i1E** [comment]
Hi @phanikumar560,

[here](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID_AllRecognizersSample/src/main/java/com/microblink/blinkid/MenuActivity.java#L892) is the sample for UAE ID front and back. You can find more information about recognizers and RecognizerBundle in [this](https://github.com/BlinkID/blinkid-android#-recognizer-concept-and-recognizerbundle) section of the documentation. 

You can pass only one RecognizerBundle at a time to the scan activity, and when scanning is done, only RecognizerBundle that has been passed to the scan activity is available for loading.

**Comment by phanikumar560** [comment]
HI Team
Even I did the same.Passed one RecognizerBundle at a time.
But when i passed the RecognizerBundle with MrtdRecognizer it worked fine for me.
When i have passed UnitedArabEmiratesIdBackRecognizer & UnitedArabEmiratesIdFrontRecognizer for RecognizerBundle  separately
 the app got crashed.
Please help on this


Thanks
Phani

**Comment by i1E** [comment]
Hi @phanikumar560,

can you please send us the full log from the device when the crash happens, like described [here](https://github.com/BlinkID/blinkid-android#other-problems)

**Comment by phanikumar560** [comment]
Hi Team,

PFB for the log requested.

2019-08-27 16:01:40.963 20188-20188/com.microblink.blinkid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.microblink.blinkid, PID: 20188
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=-1, data=Intent { (has extras) }} to activity {com.microblink.blinkid/com.microblink.blinkid.MenuActivity}: java.lang.IllegalStateException: Incompatible RecognizerBundle loaded.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4519)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
        at android.app.ActivityThread.-wrap21(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7002)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.IllegalStateException: Incompatible RecognizerBundle loaded.
        at com.microblink.entities.recognizers.RecognizerBundle.llIIlIlIIl(line:1206)
        at com.microblink.intent.llIIlIlIIl.loadFromIntent(line:91)
        at com.microblink.blinkid.MenuActivity.onActivityResult(MenuActivity.java:277)
        at android.app.Activity.dispatchActivityResult(Activity.java:7630)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4515)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563) 
        at android.app.ActivityThread.-wrap21(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1779) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:7002) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408) 


Thanks
Phani

**Comment by phanikumar560** [comment]
HI Team,
When converting the image to bitmap the bitmap is returning as empty("")
Could you please let me know the solution for this.
I have added the below code while declaring recognizers also.
 mrtdRecogniezr.setReturnFullDocumentImage(true);

I have added the below line while setting license file.
  MicroblinkSDK.setIntentDataTransferMode(IntentDataTransferMode.PERSISTED_OPTIMISED);


MrtdRecognizer.Result results = mRecognizer.getResult();

 Bitmap bitmap =results.getFullDocumentImage().convertToBitmap(); // ""
we are using Blink ID 4.8.0.1  

Thanks
Phani

**Comment by i1E** [comment]
Hi @phanikumar560,

this exception: `java.lang.IllegalStateException: Incompatible RecognizerBundle loaded` means that you are not calling `RecogniezrBundle.loadFromIntent` on the exact same RecognizerBundle instance that you have used in UISettings to start the scanning activity.

> When converting the image to bitmap the bitmap is returning as empty("")

Recognizer results can be used only after they have been loaded from intent, results are loaded to recognizer instances when you call `RecognizerBundle.loadFromIntent`, otherwise results will be empty.

**Comment by phanikumar560** [comment]
Hi Team,
I have called the below after successful loading the data from intent.Even then Iam facing the same issue.
Bitmap bitmap =results.getFullDocumentImage().convertToBitmap(); // ""
I am able to get the image from results.getFullDocumentImage() but when converting to bitmap..it is giving the empty("").
I tried checking theBlinkID-Images Sample.It is giving empty("") here also.


Thanks
Phani

**Comment by i1E** [comment]
Hi @phanikumar560,

we have tested this with our BlinkID-ImagesSample and everything worked fine, before [this line](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java#L120) we added this one and we obtained valid Bitmap image:

> Bitmap bmp = mrtdRecognizer.getResult().getFullDocumentImage().convertToBitmap();

We have tested with SDK version 4.8.0 and with the latest version 4.11.0. Please use the latest version, because we are constantly improving our SDK.

Which device you are using?

**Comment by phanikumar560** [comment]
Hi Team,
Thanks a lot for quick response.
We are using samsung Note 9.
we will check with latest version 4.11.0 and we will come back to you.

Thanks
Phani

**Comment by Brankacro** [comment]
Hello @phanikumar560,

As this is inactive, please let us know if you are having any issues. You can also contact us directly at support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello @phanikumar560 

As this issue is inactive, we will close it.
In case of any questions, feel free to contact us. As said before, you can always contact us directly at support@microblink.com We will be glad to help.

Best regards.
