### ISSUE TITLE
Exception caught on camera startup 

### ISSUE THREAD

**Issue by rsimikic** [BlinkID/blinkid-android#174]
### Description

I developed sample app that is using **RecognizerRunnerView** for document scan. Fast switching between sample app and any other app cause camera stop working. From that point on, I need to restart app in order to make scanning work again. I tried same scenario with your [sample app](https://play.google.com/store/apps/details?id=com.microblink.blinkidapp) from play store and problem exists there too.

### Environment Details

**BlinkID version:** 4.10.0

**Device model:** Google Pixel 3

**Device Android version:** 9.0

### Log file

- [mySample.log](https://github.com/BlinkID/blinkid-android/files/3540920/mySample.log) logs from my app,
- [sample.log](https://github.com/BlinkID/blinkid-android/files/3540923/sample.log) logs from blink id showing same error as in my app.

### Additional information

This is dialog message from sample app that is related to log from your sample app previously attached. 
![Screenshot_20190826-135922](https://user-images.githubusercontent.com/43816638/63689361-09229400-c80a-11e9-9862-385683ae5c9e.png)

**Comment by i1E** [comment]
Hi @rsimikic,

thank you for the report, we will investigate where is the problem and what we can do about that for the next release.

**Comment by i1E** [comment]
Hi @rsimikic,

we have fixed this in the latest SDK version, please test the BlinkID v4.11.1 and give us feedback.

**Comment by Brankacro** [comment]
Hello @rsimikic,

We are closing this as this is inactive. In case of any questions, please reopen it or you can always contact us directly at support@microblink.com

Best regards
