### ISSUE TITLE
Problem with remove Microblink Logo on scan activity ( v4.7.0). just  need a production key? 

### ISSUE THREAD

**Issue by Nalbornoz** [BlinkID/blinkid-android#175]
I need to remove the Microblink logo when launching a scan activity.
And I don't know if it's possible with a production key only.

**Comment by IvaKeresa** [comment]
Hi @Nalbornoz

The logo is the default for all of our demo license keys.
Once you set a production license key, this logo is not visible anymore.

Best regards

**Comment by Brankacro** [comment]
Hello @Nalbornoz,

We are closing this as this is inactive.
In case of any questions, please let us know. You can also contact us directly at support@microblink.com We will be more than glad to assist you.

Best regards.
