### ISSUE TITLE
Cannot set `MrzFilter.` on `MrtdCombinedRecognizer`

### ISSUE THREAD

**Issue by damienlo** [BlinkID/blinkid-android#177]
### Description

Hello, I recently started using the `MrtdCombinedRecognizer` instead of a `MrtdRecognizer`
I notice that we cannot set a MrzFilter on it.

Reading the documentation it should be possible, but the method is not exposed

> Internally, it uses DocumentFaceRecognizer for obtaining full document image and face image as the first step and then MrtdRecognizer for scanning the MRZ.

**Comment by i1E** [comment]
Hi @damienlo,

you are right, it is not exposed for the `MrtdCombinedRecognizer`, we will expose `MrzFilter` in one of the following releases.

**Comment by Brankacro** [comment]
Hello @damienlo,

We enabled setting MrzFilter on MrtdCombinedRecognizer with the version 5.2.0.
https://github.com/BlinkID/blinkid-android/blob/master/Release%20notes.md#520

Please let us know if we can be of any help. You can always contact us directly at support@microblink.com

Best regards.

**Comment by damienlo** [comment]
![Woohoo](https://media.giphy.com/media/xT5LMQ8rHYTDGFG07e/source.gif)

Looks great. thanks!
