### ISSUE TITLE
Set Scanning Region on Android

### ISSUE THREAD

**Issue by Nikola1994** [BlinkID/blinkid-android#179]
Hello, I found documentation about setting region on iOS but I couldn't find any documentation about setting scanning region in your android lib. 
So, my question is what are the parameters for method setScanningRegion and what they mean, first of all Rectangle and parameters in it, and also boolean value in this method?

Thanks,
Nikola

**Comment by i1E** [comment]
Hi @Nikola1994,

[here](https://blinkid.github.io/blinkid-android/com/microblink/view/recognition/RecognizerRunnerView.html#setScanningRegion-com.microblink.geometry.Rectangle-boolean-) you can find Javadoc for RecognizerRunnerView.setScanningRegion method.

**Comment by Nikola1994** [comment]
Thanks for helping me
