### ISSUE TITLE
MrtdRecognizer can't detect '-' and '.' characters

### ISSUE THREAD

**Issue by addam01** [BlinkID/blinkid-android#180]
Hi, I am currently using BlinkID for scanning Malaysian passport MRZ. Apparently I wasn't able to capture MRZ that has "-" or "." in the MRZ zone, even though I have set my MrtdRecognizer setAllowSpecialCharacters(true). Please advice.

### Environment Details
**BlinkID version:**
4.9.1

**Device model:**
LEAGOO M11

**Device Android version:**
Android 8.1.0

**Comment by matvidako** [comment]
Hi,

try enabling unverified results with setAllowUnverifiedResults(true).
And please send us image of the passport you're having problems with to support@microblink.com, if possible.

**Comment by addam01** [comment]
Hi, thanks for getting back to me soon. Yes, I have enabled unverified results. 
I'll email to your support team. 
Many Thanks!

**Comment by culoi** [comment]
Hello, 

MRTD only allows following characters: 

4.4    Print Specifications Machine  readable  data  shall  be  printed  in  OCR-B  type  font,  size  1,  constant  stroke  width  characters,  at  a  fixed  width  spacing of 2.54 mm (0.1 in), i.e. horizontal printing density of 10 characters per 25.4 mm (1.0 in). Printed characters are restricted to those defined in Figure 4. 

>0123456789 ABCDEFGHI JKLMNOPQR STUVWXYZ <

More information is available here: https://www.icao.int/publications/Documents/9303_p3_cons_en.pdf 

Please check the sections 4.3 and 4.6.

Dots (.) and dashes (-) are not allowed in Mrz line.

Regards

**Comment by addam01** [comment]
Hi @culoi ,
 I have looked through the release notes 
https://github.com/BlinkID/blinkid-android/blob/master/Release%20notes.md

And in version 3.16.0 and 4.7.0 have included added support for parsing Malaysian Passport IMM13P MRZ type, reading of special characters must be enabled by using MRTDRecognizerSettings.setAllowSpecialCharacters
