### ISSUE TITLE
Directapi does not return any information when run on Android Emulator.  (SDK v 4.11.1)

### ISSUE THREAD

**Issue by Nalbornoz** [BlinkID/blinkid-android#182]
### Description

I need to scan many documents using Android Emulator, to perform this I using DirectApi that not need the camera.

Well, I test the blinkid-DirectApi Sample of the 4.11.1 branch repository that you provide to the community and it does not return any scan information when I run project on Android Emulator.

### Environment Details

**BlinkID version: 4.11.1** 

**Device model: Emulator Nexus X5**

**Device Android version: API 27**

**Device ABI (processor architecture, e.g. ARMv7): CPU x86 **

### Log file

[log-blinkid-directapi.txt](https://github.com/BlinkID/blinkid-android/files/3744534/log-blinkid-directapi.txt)

**Comment by matvidako** [comment]
Hi,

thanks for reporting the issue.
It looks like this is also happening on some x86 devices, and not just emulator.

By the way, can you tell me more about your use case and why would you need to run it on emulator?

**Comment by Nalbornoz** [comment]
Hi, thanks for your response.

Well, I need run UnitTest over many documents to check the performance and quality of the direct API scan.

The process:
1) Load documents, maybe 100 or 200 images. (passports, South African documents, including videos).
2) I performed a scan over images with direct API. 
3) Generate a report with document data and cropped images generated by recognizers.

On the mobile phone, it works perfectly. the problem is the emulator.

**Comment by Brankacro** [comment]
Hello @Nalbornoz 

Sorry for not responding earlier. Please let us know if this is still an open issue for you.
You can also contact us directly at support@microblink.com
We would be more then glad to resolve all your questions and doubts.

Best regards.

**Comment by Brankacro** [comment]
Hello @Nalbornoz 

As this issue is inactive, we will close it. Feel free to contact us directly at support@microblink.com for any questions you may have.
We will gladly assist you.

Best regards,

Branka
