### ISSUE TITLE
How to remove Microblink logo

### ISSUE THREAD

**Issue by zakblacki** [BlinkID/blinkid-android#187]
I'd like to remove logo appearing 'Microblink' toast when scaning is it possible  ?
I can't find it any class or layout 
I have a demo licence 

Thanks,

**Comment by IvaKeresa** [comment]
Hello, 

This is the default for all our demo license keys.
Once you set production license keys, this logo is not visible anymore.

Best regards, 

Iva

**Comment by Brankacro** [comment]
Hello @zakblacki 

We wanted to follow up.
In case you have any additional questions, please let us know.
You can also contact us directly at support@microblink.com

Best regards.
