### ISSUE TITLE
How to pass camera without autofocus?

### ISSUE THREAD

**Issue by yanganran** [BlinkID/blinkid-android#189]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:**

**Device model:**

**Device Android version:**

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by mparadina** [comment]
Hello @yanganran 

Can you please tell me which device are you using?

Also, which recognizers are you using?

For most recognizers, it is mandatory for a device to have autofocus, in order for our SDK to work. Without autofocus, we are unable to get a clear, sharp image on which OCR is performed.

Best regards,
Milan

**Comment by Brankacro** [comment]
Hello @yanganran 

We are closing this as this is inactive. If you want to reopen the issue, please let us know.
Best regards.
