### ISSUE TITLE
How to scan the ID card in China

### ISSUE THREAD

**Issue by hanyifenghuo** [BlinkID/blinkid-android#19]
How to scan the ID card in China

**Comment by culoi** [comment]
Hi @hanyifenghuo 

At moment we support scanning of Chinese passports, visas and other documents that contains [MRZ](https://en.wikipedia.org/wiki/Machine-readable_passport)
Please follow this [link](https://github.com/BlinkID/blinkid-android#-scanning-machine-readable-travel-documents) for more details.

Best regards,
Ivan

**Comment by Cerovec** [comment]
Hi @hanyifenghuo,
Is this still an open issue to you?
Can we help you in any other way?
Thanks,
Jurica.

**Comment by culoi** [comment]
Closing the issue
