### ISSUE TITLE
Not getting Commercial code for Hongkong documents

### ISSUE THREAD

**Issue by Saikrishna521** [BlinkID/blinkid-android#190]
Hi i'm working on BlinkId latest version 5.0.0 and found that "commercial code" is not getting extracted from the OCR using BlinkIdRecognizer for HongKong front documents.Its looks like commercial code is not sent in the result callback entity for BlinkIDRecognizer.

Device-Samsungs8
Abi-arm64-v8a

Please anyone explain me why the commercial code not sent in the results.I can't find anything in release notes also.

**Comment by culoi** [comment]
Hello @Saikrishna521 

CCC number is returned with getAdditionalNameInformation property.

Also, in our latest version of the SDK that was released yesterday (BlinkID v5.2.0), you can obtain the localized name with the following property: getLocalizedName.

Please let us know how this works for you.

Regards

**Comment by Brankacro** [comment]
Hello @Saikrishna521 

Hope you resolved your issue. If you need any additional assistance from our side, please let us know.
You can always contact us directly at support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello @Saikrishna521 

As this issue is inactive, we will close it. For any questions, feel free to contact us, here or directly at support@microblink.com We will be more than glad to help.

Best regards.
