### ISSUE TITLE
Can we read "Place of Birth" from Passport in Passport recognizer?

### ISSUE THREAD

**Issue by rajubhusani** [BlinkID/blinkid-android#193]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description
Can we read "Place of Birth" from Passport using Passport recognizer?
Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:** 4.11

**Device model:** NA

**Device Android version:**NA

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by Brankacro** [comment]
Hello @rajubhusani,
sorry for the delay in reply. Regarding your question, unfortunately, the place of birth can not be read with the passport recognizer.
The PassportRecognizer is used for scanning and data extraction from the Machine Readable Zone (MRZ) of the various passport documents. This recognizer also returns face image from the passport.
Please, see on this link what data contains MRZ line https://help.microblink.com/hc/en-us/articles/360007487833-MRTD-FAQ
It would be great if you could tell us what documents and from which country you are trying to scan the documents, so we can provide you with the info what are we extracting with other recognizers.
Hope this info was helpful.
You can always contact us directly at support@microblink.com 
Thanks,
Branka

**Comment by Brankacro** [comment]
Hello @rajubhusani 

As this issue is inactive, we will close it. In case of any questions or doubts, feel free to contact us.
Also, you can contact us directly at support@microblink.com We will be more than glad to help.

Best regards.
