### ISSUE TITLE
DexGuard issue with BlinkID

### ISSUE THREAD

**Issue by subhashsanghani** [BlinkID/blinkid-android#196]
Hi,

I am using old BlinkID repository. 
com.microblink:blinkid:3.18.0@aar

I can not change it now for latest because after this version there is many changes. 

Will you help me for following crash generated when we applied DexGuard rules to our app.

**Failed to load required asset 'microblink/model_mrtd.zzip'. Program will now crash!
E/ResourceProvider.cpp:44: Failed to load resource model_mrtd. The program will now crash!**

will know me if any rules or keep condition i can add in DexGuard file so it it really very helpful to me . thanks. '

**Comment by matvidako** [comment]
Hi,

it looks like DexGuard has additional optimizations that can remove assets while our SDK requires all assets in microblink folder
We don't have access to DexGuard documentation, I recommend that you ask DexGuard support about this issue.

**Comment by Brankacro** [comment]
Hello @subhashsanghani 

Hope everything goes well. 
Did you resolve your issue in the meantime? 
In case of additional questions, please let us know. You can always contact us directly at
support@microblink.com

Best regards.

**Comment by subhashsanghani** [comment]
Thanks for your reply. Issue still not solved. it crashed while we apply dexguard. We tried all provided solutions of dexguard but still same issue.
