### ISSUE TITLE
how to get fastest result to extract text using BlinkID

### ISSUE THREAD

**Issue by pratamanidhi** [BlinkID/blinkid-android#198]
Hi.. i wan to ask about how to get fastest result to get the text from ID card. I'm using indonesian ID card to get the document number. When i tried using BlinkID sample expectially BlinkID-aMinimalSample that i've customize I only get the animation without get any output from Toast or EditText. Thankyou 

BlinkID version: v5
Device model: samsung j7 prime
Device Android version: oreo

**Comment by culoi** [comment]
Hello @pratamanidhi 

If you only need extract document number, you can set the returning of the document number.

For example, in the aMinimalSample, you can edit result processing and switch from the returning of the [getFullName](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-aMinimalSample/src/main/java/com/microblink/blinkid/MainActivity.java#L68) to [getDocumentNumber()](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdRecognizer.Result.html#getDocumentNumber--). 



But it is important that you scan the real Indonesian ID card as our SDK is optimized to work best with real documents. 

Hope this helps, if you need any additional info, please contact us directly at support@microblink.com

Regards

**Comment by galang98** [comment]
> Hello @pratamanidhi
> If you only need extract document number, you can set the returning of the document number.
> For example, in the aMinimalSample, you can edit result processing and switch from the returning of the getFullName to getDocumentNumber().
> But it is important that you scan the real Indonesian ID card as our SDK is optimized to work best with real documents.
> Hope this helps, if you need any additional info, please contact us directly at support@microblink.com
> Regards

Can you help me, when I tried to scan ID Card (Indonesian) that have Date Of Expiry is "Seumur Hidup". It doesn't scan :( . it is because of Date Of Expiry data type must be a date type ?

**Comment by culoi** [comment]
Hello @galang98 

In this case, I suggest that you use v4 of our BlinkID SDK which is available for the download here: https://github.com/BlinkID/blinkid-android/releases/tag/v4.11.1

And to set IndonesiaIdFrontRecognizer instead of the BlinkIdRecognizer.

In the v5 of our BlinkID SDK, this type of the ID card (with "Seumur Hidup" as expiry date) is not supported yet and we will support it in one of the future releases. 

For now, you can use V4. I suggest that you star and watch our repo to get instant notifications about future releases. 

If you need any assistance with setting up a v4 version and recognizer, please let me know.

Regards

**Comment by Brankacro** [comment]
Hello @galang98 

We wanted to follow up on our last communication.
Have you managed to resolve your issue?
If you need any assistance from our side, please let us know. You can always contact us directly at 
support@microblink.com

Best regards.

**Comment by Brankacro** [comment]
Hello @galang98 

As this issue is inactive we will close it. If you want to reopen the issue, please let us know.
In case of any questions, you can always contact us directly at support@microblink.com
We'll be glad to help.
Best regards,

Branka
