### ISSUE TITLE
Is overwriting lifecycle methods for a custom UI still necessary?

### ISSUE THREAD

**Issue by Farbklex** [BlinkID/blinkid-android#199]
In the readme you write under the section [Custom UX with RecognizerRunnerView](https://github.com/BlinkID/blinkid-android/blob/master/README.md#-custom-ux-with-recognizerrunnerview) that we should overwrite our lifecycle methods.

> Override your activity's onStart, onResume, onPause, onStop and onDestroy methods and call RecognizerRunnerView's lifecycle methods start, resume, pause, stop and destroy

Is this still true or can we instead use the `setLifecycle` method? It looks like it already takes care of calling the right lifecycle methods for us.

Using a lifecyle owner would prevent some lines of boilerplate code and should be included in the readme.

**Comment by matvidako** [comment]
Hi,

you are right, you can just use `setLifecycle`.
Thanks for reporting it, we forgot to update readme after adding the new method.
