### ISSUE TITLE
v4 support library

### ISSUE THREAD

**Issue by dougbergh** [BlinkID/blinkid-android#2]
Do you plan a version that doesn't depend on the v4 support library? v7 appcompat library is OK..

**Comment by DoDoENT** [comment]
Hi dougbergh,

v4 support library is required for BlinkOCRActivity (i.e. for performing OCR of text segments). If you do not plan to use this activity in your app, or if you plan creating custom camera overlay, then you do not need to add v4 support dependency. Be aware that if you do that, attempting to start BlinkOCRActivity will crash your app.

**Comment by DoDoENT** [comment]
Hi @dougbergh,

several last releases now require only appcompat-v7 and we also added [transitive dependencies support](https://github.com/BlinkID/blinkid-android#mavenIntegration) in latest release. 

Can we close this issue now?
