### ISSUE TITLE
How do i remove the logo of Microblink

### ISSUE THREAD

**Issue by neha-eng** [BlinkID/blinkid-android#203]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:**

**Device model:**

**Device Android version:**

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by mparadina** [comment]
Hi @neha-eng 

The logo is part of our demo license key.
It is removed once the user purchases the production license key. 

To purchase the production license key, you can always contact our Sales Team at sales@microblink.com

If you have any further questions, feel free to ask.

Regards,
Milan

**Comment by Brankacro** [comment]
Hi @neha-eng 
Hope that info was helpful. We will solve this issue. If you will have any questions, feel free to ask.
You can always contact us directly at support@microblink.com
Best regards,
Branka
