### ISSUE TITLE
How can i save the scanned image to a folder in my gallery. 

### ISSUE THREAD

**Issue by neha-eng** [BlinkID/blinkid-android#204]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:**

**Device model:**

**Device Android version:**

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by mparadina** [comment]
Hi @neha-eng 

In the BlinkID samples folder, you have an ImagesSample folder. This sample is made with an intent to save the scanned images to external storage. You can see the example here:

https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java#L38

Hope this helped. If you have come across any difficulties, feel free to ask or contact us directly at support@microblink.com

Regards,
Milan

**Comment by nanaluz** [comment]
#205

**Comment by neha-eng** [comment]
Hi @mparadina 
Thankyou for help!
But how do I save it to my gallery

**Comment by mparadina** [comment]
Hi @neha-eng 

In your ImagesSample, you have the following methods to store the images to an image folder:

This is the method to store the scanned images to your images folder:
https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java#L127-L201

Also, this is the method that stores the images and creates the image folder where you store them:
https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java#L151

This is how you store the image:
https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java#L117-L120

If you have any further questions, feel free to ask.

Regards,
Milan

**Comment by Brankacro** [comment]
Hi @neha-eng 

Hope you resolved your issue and that everything works fine.
We will close the issue for now, but let us know if you want to reopen it.
For any further questions, do not hesitate to contact us. Also, feel free to contact us directly at support@microblink.com We will gladly assist you.

Best regards,

Branka
