### ISSUE TITLE
Switch BlinkIdCombinedRecognizer to the back side manually

### ISSUE THREAD

**Issue by AndriiKarpenko** [BlinkID/blinkid-android#205]
I'm trying to use BlinkIdCombinedRecognizer with DirectApi. 
But don't understand how to switch recognizer to the back side?

I've implemented 
`
metadataCallbacks.setFirstSideRecognitionCallback(() -> {
     Toast.makeText(context, "FINISHED!", Toast.LENGTH_LONG).show();
});
`

But after getting the callback, the recognizer keeps recognizing only the front side.

**BlinkID version: 5.2.0

**Comment by culoi** [comment]
Hello @AndriiKarpenko 

DirectAPI is designed to work on the single image. It will not work for the combined recognizer as recognition will work only on the first image that is detected.

Which document are you trying to scan?

Regards

**Comment by AndriiKarpenko** [comment]
Hello @culoi! It's Germany Id Card

**Comment by culoi** [comment]
Hi @AndriiKarpenko 

And both side scan is required? Which info do you need to extract from the Germany ID?

Regards

**Comment by AndriiKarpenko** [comment]
According to our UI:
1) User should scan the first side of the document;
2) After getting the results user checks photo's quality of the front side on a separate Activity
3) After that app starts scanning the back side of the document.
4) After getting the results user checks photo's quality of the back side on a separate Activity

How can I implement this flow? 
As I understand, I'm limited by using only `RecognizerRunnerView`. But how can I pass the state of recognizer from one Activity to another?

**Comment by AndriiKarpenko** [comment]
I was able to make it with 4th version, but 5th version completely broke our flow :(

**Comment by culoi** [comment]
Hi @AndriiKarpenko 

We also do have v5 of the SDK with all the features from v4, but is distributed via dashboard. Please register to our dashboard (www.microblink.com/signup) and contact us directly with your email to support@microblink.com

Regards

**Comment by nanaluz** [comment]
#

**Comment by nanaluz** [comment]
#205

**Comment by Brankacro** [comment]
Hello @AndriiKarpenko 

As this issue is inactive, we will solve it.
For any further questions, please contact us directly with your e-mail to support@microblink.com We will be more than glad to assist you.

Best regards,

Branka
