### ISSUE TITLE
FrameGrabberRecognizer + BlinkIdCombinedRecognizer  = issue scanning the SECOND_SIDE of a document

### ISSUE THREAD

**Issue by damienlo** [BlinkID/blinkid-android#211]
### Description

I am trying to use a combination `FrameGrabberRecognizer` + `BlinkIdCombinedRecognizer`
I am using a French National ID for my tests

Expected: 
When `BlinkIdCombinedRecognizer` is the only recognizer, it calls `onScanningDone` after both side were scanned.

Actual:
When the recognizer bundle is `FrameGrabberRecognizer` + `BlinkIdCombinedRecognizer`:
`onScanningDone` is called as soon as the Front side of the ID is scanned.

### Environment Details

**Blink Id version: 5.2.0:**

**Samsung s8:**

**Android. version: 9.0**

### Additional information

Combination of `FrameGrabberRecognizer` + `UsDlCombinedRecognizer` works as expeted

**Comment by matvidako** [comment]
Hi,

in 5.2.0 we support only front side scanning for French ID. You'll need to update to at least 5.3.0 to scan the back side.
You can check the full list of supported documents [here](https://github.com/BlinkID/blinkid-android/blob/master/documentation/BlinkIDRecognizer.md).

**Comment by damienlo** [comment]
Updating to 5.4 almost fixed my problem :/ 

I can scan both side, but I am not receiving any OCR data.
It only happens when I have a specific scanning region set.

 
That issue is reproductible with the `CustomCombinedSample` app
You can find a modified version of that sample app with the said bug here : 

https://gist.github.com/damienlo/c88b1181d9c7aaaa29721931484f8659

**Comment by matvidako** [comment]
Hi,

thanks for providing the code.
Unfortunately, `BlinkIDRecognizer` currently does not support ocr point detection.

Can you tell me why do you need this feature?

**Comment by eddieMicroblink** [comment]
Hi @damienlo 

Just a quick follow-up on this, are you still experiencing the previously mentioned issues?

Regards,
Edhem

**Comment by damienlo** [comment]
I will retest with the latest version. If the issue persist I will upload a sample project and reopen this Issue
