### ISSUE TITLE
How to get cropped face on MyKad?

### ISSUE THREAD

**Issue by zahinsarif** [BlinkID/blinkid-android#212]
Hi, I trying to get cropped face on MyKad. I already make some research and read this https://github.com/BlinkID/blinkid-android/issues/89. But no clue at all. Can you give example code for it? Thank you.

**Comment by matvidako** [comment]
Hi,

you just need to call `setReturnFaceImage(true)` on your recognizer object.
You can see an example for `BlinkIdCombinedRecognizer` in [images sample app](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-ImagesSample/src/main/java/com/microblink/blinkid/MainActivity.java).
