### ISSUE TITLE
Suggest us an application to be used for our requirements in blink ID android

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-android#214]
Hi Team,
We have used blink id UI Android for our project for the below requirements.Since we got an update that blink ID UI android is no longer updated with latest versions, so we want to move our project to blink ID android.
**Requirements** :
Scan Passport of all the countries and should return all the field values along with image base64 content.
Scan Emirates ID of United Arab Emirates and should return all the field values along with image base64 content.

Since we have many projects for android 
* BlinkID-aMinimalSample 
* BlinkID-AllRecognizersSample 
* BlinkID-CustomCombinedSample 
* BlinkID-CustomUISample 
* BlinkID-DirectApiSample 
* BlinkID-ImagesSample
* BlinkID-OverlaySample 

We are planning to use passportRecognizer to get passport results
& BlinkIdCombinedRecognizer for getting EMirates ID card results.
We have some custom UI( like we should have scanning part should be in the center of the screen and covering up & bottom content with our app related stuff )

Could you please suggest us which application to use in our case for  best results.

Thanks
Phani

**Comment by mparadina** [comment]
Hi @phanikumar560 

From version 5.5 (currently, the latest version) of BlinkID, we've added the support of reading passport and traveling visa documents in the BlinkID recognizer, so you can use the BlinkIDCombinedRecognizer for both passport and Emirates ID scanning.

Regarding the Custom UI, we recommend trying the BlinkID-CustomUISample, where you can use your own custom overlay for the scanning process.
Also to note, we are now doing our own internal document classification and the SDK now automatically classifies the document type and the country from which is the document

We recommend trying out the BlinkID 5.5:
https://github.com/BlinkID/blinkid-android/releases/tag/v5.5.0

Regards,
Milan

**Comment by anjapenic** [comment]
Hi @phanikumar560,

Since this issue is inactive, we're closing it. If you need any further assistance feel free to open a new issue or contact us at support@microblink.com. 

Regards,
Anja
