### ISSUE TITLE
Support for arabic documents

### ISSUE THREAD

**Issue by m-movo** [BlinkID/blinkid-android#216]
Is their planned support for arabic text in arabic documents ex. Egypt ID.

**Comment by mparadina** [comment]
Hi @passid2019 

We currently do not know when you will we support Arabic letters.
However, we have it on our roadmap, but unfortunately, we can't give you an exact date when will we support it.

Also, if it is of any help, we read the document number and personal ID number for the front side and the date of issue, date of expiry, and the ID number from the backside of the Egypt ID.

Let me know if you have any additional questions.

Regards,
Milan

**Comment by eddieMicroblink** [comment]
Hi @passid2019 

Just a quick follow-up on this, have you been able to extract the aforementioned data?
You can also use MrtdRecognizer to retrieve data from documents with MRZ.

Regards,
Edhem

**Comment by passid2019** [comment]
@eddieMicroblink We extracted only the data that was mentioned above by @mparadina, but we couldn't extract the info that we asked about as it's not supported yet. As for MRZ that document we are after doesn't contain MRZ.

**Comment by krizaa** [comment]
Hi @m-movo, we've added support for reading the Arabic script in BlinkID v6.0.0. You can try it out and let us know if you have any issues :)
