### ISSUE TITLE
Suggestion on passport recognizer in blinkID android

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-android#217]
Hi Team,

We have below requirements.
Scan Passport of all the countries and should return all the field values along with image base64 content.
Scan Emirates ID of United Arab Emirates and should return all the field values along with image base64 content.

So we have opted for BlinkID-CustomCombined Sample.
If we use passport recognizer in this project scanning itself is not happening. Could you please suggest on this?

Is there any difference between passport recognizer and combined recognizer in performance?

Thanks
Phani

**Comment by matvidako** [comment]
Hi Phani,

PassportRecognizer is a recognizer that expects face image and mrz on a single document side while MrtdCombined recognizer first scans face image and then reads mrz.
The sample you're using is designed to support combined case, scanning front side and then scanning back side.
As for performance, they should be about the same.

Have you tried using BlinkIdCombinedRecognizer with our default UI? It supports scanning both Emirates ID and passports.

**Comment by phanikumar560** [comment]
Hi Team,
Thanks for the update.
Our project is developed in Kony. So we create .aar files from sample project and integrate with kony. 
when we tried with the BlinkIdCombinedRecognizer in the sample project it is working fine. But when integrated with main project passport scan is not happening. But in the same place emirates ID is placed scanning is happening.
Could you suggest us are we missing any thing while creating aar files?


When we try to use passport recognizer scanning is not happening. 
When we use the below line in java file passport recognizer is working fine and even when we integrate in our project it is working fine..But here the problem is UI. UI should be like as that of Custom combined sample.
 ActivityRunner.startActivityForResult(this, MY_BLINKID_REQUEST_CODE, settings);

Please suggest.



Thanks
Phani

**Comment by matvidako** [comment]
Hi,

if you're using BlinkIdCombinedRecognizer make sure that you update to BlinkID 5.5. Older versions do not support passports.

**Comment by phanikumar560** [comment]
Hi Team,

I have upgraded to v5.5.0.
The same code works for Emirates ID scan.But passport is not scanned when integrated in our application.

Can we use passportRecognizer in BlinkID-customCombined sample app?


Thanks
Phani

**Comment by mparadina** [comment]
Hi @phanikumar560 

Do you get any kind of warning message when you try to scan the passport?
Also, do you get any kind of exceptions or nothing happens?

Regards,
Milan

**Comment by phanikumar560** [comment]
Hi,

I didn't get any warning message while using passportRecognizer.

Thanks
Phani

**Comment by mparadina** [comment]
Hi @phanikumar560 

Can you please contact us directly at support@microblink.com so that we can inspect the license key that you are currently using in your project?
There is a chance that certain rights may not be enabled in your license key, thus resulting in unsuccessful scans with the passport.

Regards,
Milan

**Comment by phanikumar560** [comment]
Hi Team,

Any update on how to use passport recognizer in BlinkID-CustomCombinedSample app.
I am not getting any errors in the application but when we try to scan the passport it is not happening.
/////////------COde snippet- starts--------//////
package com.microblink.blinkid;

import android.app.Activity;
import android.content.Intent;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Environment;
import android.os.Parcelable;
import android.util.Base64;
import android.util.Log;
import android.view.View;
import android.widget.RelativeLayout;
import android.widget.TextView;
import android.widget.Toast;


import com.microblink.entities.Entity;
import com.microblink.entities.recognizers.Recognizer;
import com.microblink.entities.recognizers.blinkid.imageresult.CombinedFullDocumentImageResult;
import com.microblink.entities.recognizers.blinkid.mrtd.MrtdRecognizer;
import com.microblink.entities.recognizers.blinkid.mrtd.MrzResult;
import com.microblink.entities.recognizers.blinkid.passport.PassportRecognizer;
import com.microblink.result.extract.BaseResultExtractor;
import com.microblink.result.extract.RecognitionResultEntry;
import com.microblink.entities.recognizers.RecognizerBundle;
import com.microblink.entities.recognizers.blinkid.mrtd.MrtdCombinedRecognizer;
import com.microblink.entities.recognizers.blinkid.usdl.UsdlCombinedRecognizer;
import com.microblink.entities.recognizers.blinkid.generic.BlinkIdCombinedRecognizer;
import com.microblink.entities.recognizers.Recognizer.Result;


import com.microblink.hardware.camera.CameraType;
import com.microblink.menu.MenuListItem;
import com.microblink.menu.ResultHandlerMenuActivity;
import com.microblink.result.activity.RecognizerBundleResultActivity;
import com.microblink.result.extract.blinkid.generic.BlinkIDCombinedRecognizerResultExtractor;
import com.microblink.results.date.Date;
import com.microblink.util.ImageSettings;
import com.microblink.util.ImageUtils;
import com.microblink.util.RecognizerCompatibility;
import com.microblink.util.RecognizerCompatibilityStatus;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.List;
import java.util.Set;

public class ScanPassport extends ResultHandlerMenuActivity {
   // private BlinkIdCombinedRecognizer mRecognizer;
    private PassportRecognizer passportRecognizer;
    private RecognizerBundle mRecognizerBundle;
    public static final int MY_BLINKID_REQUEST_CODE = 0x101;
    Hashtable<String, String> tempValuesOfPassport = new Hashtable<String, String>();
    Hashtable<String, String> param1 = new Hashtable<String, String>();

    @Override
    protected String getTitleText() {
        return getString(R.string.app_name);
    }

    @Override
    protected boolean isScanRequestCode(int code) {
        return code == MY_BLINKID_REQUEST_CODE;
    }

    @Override
    protected Class<?> getResultActivityForRequestCode(int requestCode) {
        return RecognizerBundleResultActivity.class;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // check if BlinkID is supported on the device
        RecognizerCompatibilityStatus supportStatus = RecognizerCompatibility.getRecognizerCompatibilityStatus(this);
        if (supportStatus != RecognizerCompatibilityStatus.RECOGNIZER_SUPPORTED) {
            Toast.makeText(this, "BlinkID is not supported! Reason: " + supportStatus.name(), Toast.LENGTH_LONG).show();
        }
       // mRecognizer = new BlinkIdCombinedRecognizer();
        passportRecognizer=new PassportRecognizer();

        // bundle recognizers into RecognizerBundle
      //  mRecognizerBundle = new RecognizerBundle(mRecognizer);
        mRecognizerBundle = new RecognizerBundle(passportRecognizer);

    }

    @Override
    protected List<MenuListItem> createMenuListItems() {
        List<MenuListItem> items = new ArrayList<>();

        items.add(createMenuListItem("BlinkID combined", ImageSettings.enableAllImages(new BlinkIdCombinedRecognizer())));


        return items;
    }

    private MenuListItem createMenuListItem(String title, final Recognizer recognizer) {
        return new MenuListItem(title, new Runnable() {
            @Override
            public void run() {
                Intent intent = new Intent(ScanPassport.this, CustomVerificationFlowActivity.class);
                mRecognizerBundle = new RecognizerBundle(recognizer);
                mRecognizerBundle.saveToIntent(intent);
                intent.putExtra(CustomVerificationFlowActivity.EXTRAS_BEEP_RESOURCE, R.raw.beep);
                intent.putExtra(CustomVerificationFlowActivity.EXTRAS_COMBINED_CAMERA_TYPE, (Parcelable) CameraType.CAMERA_BACKFACE);
                startActivityForResult(intent, MY_BLINKID_REQUEST_CODE);
            }
        });
    }




    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // onActivityResult is called whenever we returned from activity started with startActivityForResult
        // We need to check request code to determine that we have really returned from BlinkID activity
        if (requestCode != MY_BLINKID_REQUEST_CODE) {
            return;
        }

        if (resultCode == Activity.RESULT_OK) {
            // OK result code means scan was successful
            Recognizer recognizer = mRecognizerBundle.getRecognizers()[0];
            Entity.Result result = recognizer.getResult();


            tempValuesOfPassport.put("DOCUMENT_NUMBER", "");
            tempValuesOfPassport.put("DOCUMENT_CODE", "");
            tempValuesOfPassport.put("DATE_OF_EXPIRY", "");
            tempValuesOfPassport.put("PRIMARY_ID", "");
            tempValuesOfPassport.put("SECONDARY_ID", "");
            tempValuesOfPassport.put("NATIONALITY", "");
            tempValuesOfPassport.put("SEX", "");
            tempValuesOfPassport.put("MRZ_TEXT", "");
            tempValuesOfPassport.put("OPTIONAL_FIELD_1", "");
            tempValuesOfPassport.put("DATE_OF_BIRTH", "");
            if (!(result instanceof PassportRecognizer.Result)) {
                Toast.makeText(this, "Nothing scanned!", Toast.LENGTH_SHORT).show();
                return;
            }

            MrzResult mrzResult = ((PassportRecognizer.Result)result).getMrzResult();
            tempValuesOfPassport.put("DOCUMENT_NUMBER", mrzResult.getDocumentNumber().toString());
            tempValuesOfPassport.put("DOCUMENT_CODE", mrzResult.getDocumentCode().toString());
            tempValuesOfPassport.put("DATE_OF_EXPIRY", mrzResult.getDateOfExpiry().toString());
            tempValuesOfPassport.put("PRIMARY_ID", mrzResult.getPrimaryId().toString());
            tempValuesOfPassport.put("SECONDARY_ID", mrzResult.getSecondaryId().toString());
            tempValuesOfPassport.put("DATE_OF_BIRTH", mrzResult.getDateOfBirth().toString());
            tempValuesOfPassport.put("NATIONALITY", mrzResult.getNationality().toString());
            tempValuesOfPassport.put("SEX", mrzResult.getGender().toString());
            tempValuesOfPassport.put("MRZ_TEXT", mrzResult.getMrzText().toString());
            tempValuesOfPassport.put("OPTIONAL_FIELD_1", mrzResult.getOpt1().toString());
            tempValuesOfPassport.put("ISSUER", mrzResult.getIssuer().toString());



            /* Passport Image Captured */
           // CombinedFullDocumentImageResult combinedFullDocumentImageResult = (CombinedFullDocumentImageResult) result;
            Bitmap bitmap = ((PassportRecognizer.Result) result).getFullDocumentImage().convertToBitmap();

          //  Bitmap bitmap = combinedFullDocumentImageResult.getFullDocumentFrontImage().convertToBitmap();
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.JPEG, 25, byteArrayOutputStream);
            byte[] byteArray = byteArrayOutputStream.toByteArray();
            if (byteArray != null) {
                String encodedDataPassportImage = Base64.encodeToString(byteArray, Base64.DEFAULT);
                Log.d("passport results", "arr: " + encodedDataPassportImage);
                param1.put("imgData", encodedDataPassportImage);
            }

            onScanSuccess(data);
        } else {
            // user probably pressed Back button and cancelled scanning
            onScanCanceled();
        }
    }

    private void onScanSuccess(Intent data) {
        // update recognizer results with scanned data
        mRecognizerBundle.loadFromIntent(data);

        param1.put("DocumentNumber", tempValuesOfPassport.get("DOCUMENT_NUMBER"));
        param1.put("DocumentCode", tempValuesOfPassport.get("DOCUMENT_CODE"));
        param1.put("dateOfExp", tempValuesOfPassport.get("DATE_OF_EXPIRY").replaceAll("\\.", "/").substring(0, tempValuesOfPassport.get("DATE_OF_EXPIRY").replaceAll("\\.", "/").length() - 1));
        //  param1.put("dateOfExp",tempValuesOfPassport.get("DATE_OF_EXPIRY"));
        param1.put("PrimaryId", tempValuesOfPassport.get("PRIMARY_ID"));
        param1.put("SecondaryId", tempValuesOfPassport.get("SECONDARY_ID"));
        param1.put("dob", tempValuesOfPassport.get("DATE_OF_BIRTH").replaceAll("\\.", "/").substring(0, tempValuesOfPassport.get("DATE_OF_BIRTH").replaceAll("\\.", "/").length() - 1));
        param1.put("Nationality", tempValuesOfPassport.get("NATIONALITY"));
        param1.put("Sex", tempValuesOfPassport.get("SEX"));
        param1.put("MRTDRaw", tempValuesOfPassport.get("MRZ_TEXT"));
        param1.put("Opt1", tempValuesOfPassport.get("OPTIONAL_FIELD_1"));
        param1.put("Issuer", tempValuesOfPassport.get("ISSUER"));
    }

    private void onScanCanceled() {
        Toast.makeText(this, "Scan cancelled!", Toast.LENGTH_SHORT).show();
    }



}

/////////------COde snippet---Ends------//////

Please review this and suggest us.



Thanks
Phani

**Comment by culoi** [comment]
Hi @phanikumar560 

As Matej mentioned above, CustomCombined will not work with the PassportRecognizer as it is made to work only with CombinedRecognizer, and it is expecting front and the back side of the document. From the passport, we only scan front side.

However, as BlinkIdCombined from version 5.5.0 support scanning of the passport internally, you can use the BlinkIdCombinedRecognizer to scan all passports and EIDA documents. 

If you need a new demo license key which enables scanning of the passport from the BlinkIDCombinedRecognizer, please contact us at support@microlink.com or log in to your account on our dashboard and generate a new demo key. 

Bes regards and stay safe!

**Comment by phanikumar560** [comment]
HI Team,

Thanks a lot for the solution.

We have two screens one for scanning passport and the other for scanning emirates ID.

The problem is can we have to restrict the Emirates ID scan in passport scanning screen
and vice versa.

Please provide us solution for this.?


Thanks
Phani

**Comment by i1E** [comment]
Hi @phanikumar560,

> But here the problem is UI. UI should be like as that of Custom combined sample.

Instead of using `BlinkIdUISettings`, you should use [`DocumentVerificationUISettings`](https://github.com/BlinkID/blinkid-android#-documentverificationuisetting) to get the same UI as in the Custom combined sample.

**Comment by phanikumar560** [comment]
Hi Team,
Is there any solution for this issue?
**https://github.com/BlinkID/blinkid-android/issues/217#issuecomment-654683246**

Thanks
Phani

**Comment by i1E** [comment]
Hi @phanikumar560,

you should set the classFilter on the `BlinkIdCombinedRecognizer` by using [BlinkIdCombinedRecognizer.setClassFilter](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdCombinedRecognizer.html#setClassFilter-com.microblink.entities.recognizers.blinkid.generic.ClassFilter-) method. ClassFilter is used to filter out documents, based on the document's [ClassInfo](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/classinfo/ClassInfo.html).

**Comment by phanikumar560** [comment]
Hi Team,
Could you please provide us the information on the document code of the UAE Emirates ID card & passport.

For Example :
 String DocumentCode=mrzResult.getDocumentCode().toString();

Just want to confirm that DocumentCode for all emirates IDs will be same and the value is "IL". Could you please confirm?
Just want to confirm that DocumentCode for all passport will always start with "P". Could you please confirm?


Thanks
Phani

**Comment by matvidako** [comment]
Hi, 

if you just want to check document type, you can use [getDocumentType](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/mrtd/MrzResult.html#getDocumentType--) method.
For ID it should be set to `MRTD_TYPE_IDENITY_CARD` and for passport to `MRTD_TYPE_PASSPORT`.

Or do you need something else?

Regards,
Matej

**Comment by phanikumar560** [comment]
Hi 
I don't want to check document type.
I Want to get documentCode for UAE emirates ID. When we scanned for some of the UAE IDs it is returning "IL" as a code will that be constant across all UAE emirates ID cards??

Thanks
Phani

**Comment by matvidako** [comment]
Hi,

there are 2 very similar looking but different documents,
resident ID card - always has "IL" document code, and ID card - always has "ID" document code.

**Comment by matvidako** [comment]
@phanikumar560 
update:
resident ID card can also have "IR" document code.

In general, according to MRTD standard, all letters except V and P are allowed after I
so you should double check official documentation for the documents you are scanning.

**Comment by phanikumar560** [comment]
Hi Team,

Is there a way where we have to restrict the scanning when other document is placed instead of UnitedArabEmiratesFront and UnitedArabEmiratesBack ID cards just like the old UnitedArabEmiratesFrontRecognizer & UnitedArabEmiratesBackRecognizer does?

We felt getting the documentCode and comparing with "IL" will solve our purpose.. So we just need 
documentCode values for only UnitedArabEmiratesCard value only.??


If not could you please provide us any unique value from MRTD recognizer results so that we can go ahead with it?


Thanks
Phani

**Comment by eddieMicroblink** [comment]
Hi @phanikumar560 

You can use ClassFilter to decide which documents you want to scan.
Please take a look at the [documentation](https://blinkid.github.io/blinkid-android/index.html?com/microblink/entities/recognizers/blinkid/generic/ClassFilter.html)
You will be able to filter documents by country, region and document type.

Regards,
Edhem

**Comment by anjapenic** [comment]
Hello @phanikumar560,

Since this issue is inactive, we’re closing it. If you need any further assistance feel free to open a new issue or contact us at support@microblink.com.

Regards,
Anja
