### ISSUE TITLE
Auto Detect Different Type of Cards

### ISSUE THREAD

**Issue by leeyikkong** [BlinkID/blinkid-android#22]
Hi, 

may I know is it possible to scan the card and it will auto detect which card it is? For example, I call the scanning activity, and during the scanning process, it will auto detect the object that I scanned whether is an identity card or passport. Is that possible??

Thank you.

**Comment by i1E** [comment]
Hi @leeyikkong,

you can activate multiple recognizers at the same time, for example you can activate [MRTDRcognizer](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/MRTDRecognizerSettings.html) together with recognizers for other supported documents. This will significantly slow down the scanning process and try to enable as few recognizers as possible for your use case. If you are scanning side of the ID card where MRZ is placed, probably you will obtain only result from MRTD recognizer, you can [enable obtaining of multiple scan results on single image](https://github.com/BlinkID/blinkid-android#setallowmultiplescanresultsonsingleimageboolean).

Second approach is to use only MRTDRecognizer and check document type by calling [getDocumentType](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/MRTDRecognitionResult.html#getDocumentType--) method on obtained [MRTDRecognitionResult](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/MRTDRecognitionResult.html).

**Comment by leeyikkong** [comment]
May I know where should I declare the MRTDRecognitionResult?
if the RecognitionResult i get at onActivityResult() method.
thank you.

**Comment by leeyikkong** [comment]
I think I found the solution already. just declare a static variable to get the result after the scanning.
thanks

**Comment by i1E** [comment]
Hi @leeyikkong,

recognizers produce different result types (each document type has its corresponding result type). When scanning is done, you can use `instanceof` operator to check result type - in [onScanningDone](https://blinkid.github.io/blinkid-android/com/microblink/view/recognition/ScanResultListener.html#onScanningDone-com.microblink.recognizers.RecognitionResults-) method if you are performing [custom UI integration](https://github.com/BlinkID/blinkid-android#-embedding-recognizerview-into-custom-scan-activity), or in `onActivityResult` method if you are using one of the provided scan activities from the SDK.

Best regards

**Comment by leeyikkong** [comment]
yes..that is what I did. THanks alot.
