### ISSUE TITLE
Support for birth certificate

### ISSUE THREAD

**Issue by phanikumar560** [BlinkID/blinkid-android#221]
Hi Team,

Could you please let us know whether micro blink is having support for birth certificate in android & ios?

We have a requirement to scan the date of birth certificate capture it and send the base 64 of that captured image.

Kindly let us know the above scenario is possible with the microblink?

Thanks
Phani

**Comment by matvidako** [comment]
Hi,

please contact us directly at support@microblink.com and we'll help.

Thanks

**Comment by anjapenic** [comment]
Hello @phanikumar560,

Since this ticket is inactive for some time, we're closing it. If you need any further assistance, feel free to open a new one or contact us at support@microblink.com.

Best regards,
Anja
