### ISSUE TITLE
Accept only Belgium ID Card and Resident ID

### ISSUE THREAD

**Issue by SimonRolin** [BlinkID/blinkid-android#228]
Hi, 

I'm trying to figure out how to only accept Belgian ID Card and Resident ID with the BlinkIdCombinedRecognizer ? 

Thanks a lot in advance !

**Comment by matvidako** [comment]
Hi,

you can set a [ClassFilter](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/BlinkIdCombinedRecognizer.html#setClassFilter-com.microblink.entities.recognizers.blinkid.generic.ClassFilter-).

You'll get a callback with `ClassInfo` object, just check its type and country.
