### ISSUE TITLE
Battery Consumption

### ISSUE THREAD

**Issue by k0shk0sh** [BlinkID/blinkid-android#23]
I would like to know how much does BlinkId impact on the battery? 
When we awhile ago started developing on the Template module which we regularly had to do some testing, we discovered that the BlinkId impact the battery life pretty much, is there anyway future enhancement that can actually reduce the library battery consumption? 

Thanks.

**Comment by culoi** [comment]
Dear k0shk0sh,

BlinkID uses all processing power it has available to deliver scan results as quickly as possible. Putting CPU to max speed causes increased battery drainage - this is expected. BlinkID is not designed with idea that scanning will be continuous while device is on battery - it is designed with idea that user starts the scan, scans the document as quickly as possible and stops the scan. Our future enhancements will go in a way of harnessing even more power from device to yield both better accuracy and speed. Doing any battery life optimisation will make BlinkID just a lot slower and less accurate. That would then mean that user will need to perform multiple scans (each of which will be slower) to scan the document, thus actually spending more battery charge as with current setup.

**Comment by k0shk0sh** [comment]
@culoi thanks for the reply, is there anyway where i can tell BlinkId to scan these N frames per second? make it a bit slower but still as fast as possible?

**Comment by culoi** [comment]
@k0shk0sh You can achieve that by using Direct API with custom camera management, as shown in this example: https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDirectApiDemo/src/main/java/com/microblink/blinkid/demo/customcamera

**Comment by k0shk0sh** [comment]
@culoi I don't see that this issue should be open any longer. thanks for your help tho.
