### ISSUE TITLE
BlinkId Recognizer unable to retrieve a Passport Document Number

### ISSUE THREAD

**Issue by ahshingx95** [BlinkID/blinkid-android#230]
Hi,

I was trying to scan a Singaporean Passport found in Google as a test sample, but it doesn't get the Document Number, "K0000000E". I have tried getMrzResult().getDocumentNumber(), result.getVizResult().getDocumentNumber(), and result.getDocumentNumber(). Returns empty.

I have tried on another Passport sample found in Google as well but able to get the Document Number.

This is the link of the Passport Image which cannot get the Document Number. [https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Biodata_page_of_Singapore_Passport.jpg/440px-Biodata_page_of_Singapore_Passport.jpg](url)

Please advice me on how to get the Document Number, I testing a lots of results but failed.

Thanks and Regards,
Shing

**Comment by SandraKuzmic** [comment]
Hi @ahshingx95 

by default, this field is currently anonymized which means we don't extract it. You can disable anonymization by setting `anonymizationMode` in BlinkIdRecognizer to `AnonymizationMode.None` or `AnonymizationMode.ImageOnly`.

More info about anonymization can be found [here](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/AnonymizationMode.html).

Best regards,
Sandra

**Comment by ahshingx95** [comment]
Thank you for your reply, I have received your email too. It works with **AnonymizationMode.None**. Thanks!
