### ISSUE TITLE
How to use External Camera for Scan

### ISSUE THREAD

**Issue by Robotrator** [BlinkID/blinkid-android#234]
I am running the project on my Robot which has two Cameras. It is accessing default camera but I want to switch the preview to the other Camera. From where I can change the Camera, which activity for camera preview?

RecognizerBundleResultActivity.java & BaseResultActivity.java, these two files I explored for Switching Camera but it seems no camera activity there. 

Can you please assist in this?

**Comment by i1E** [comment]
Hi @NumanGillani-jackys,

you can set camera type by using [BlinkIdUISettings.setCameraSettings](https://blinkid.github.io/blinkid-android/com/microblink/uisettings/UISettings.html#setCameraSettings-com.microblink.uisettings.CameraSettings-) method. 

CameraSettings.Builder has method [setType](https://blinkid.github.io/blinkid-android/com/microblink/uisettings/CameraSettings.Builder.html#setType-com.microblink.hardware.camera.CameraType-), by using this method you can choose between CameraType.CAMERA_DEFAULT, CameraType.CAMERA_BACKFACE and CameraType.CAMERA_FRONTFACE.

**Comment by anjapenic** [comment]
Hi @Robotrator,

Since this issue is inactive, we're closing it. If you need any further assistance feel free to open a new issue or contact us at support@microblink.com.

Regards,
Anja
