### ISSUE TITLE
USDL / StateId support for BlinkIdCombinedRecognizer

### ISSUE THREAD

**Issue by damienlo** [BlinkID/blinkid-android#239]
### Description

Hello we started seeing support from BlinkIdCombinedRecognizer for USDL and State ID.
After running multiple tests here is what I was able to scan: 

**USDL**
Real document  : Oklahoma  -> OK
Photo : Delaware -> OK 
Photo : Georgia --> OK
Photo : Montana -> cannot scan front
Photo : Florida --> cannot scan back
Photo : Texas --> cannot scan back
Photo : Washington --> OK
 Photo : Indiana --> cannot scan back
 Photo : Illinois --> cannot scan back
Photo :  Maryland -> cannot scan front
Photo : Hawaii -> OK 
Photo : Tennessee -> OK 
Photo : Connecticut -> cannot scan back 
Photo : New Hampshire -> cannot scan front
Photo : New York State -> cannot scan back
Photo : California -> OK 
Photo : Minnesota -> cannot scan front
Photo : Utah -> cannot scan back
 
 **STATE ID**
 
 Photo : Arkansa -> OK
Photo : California -> OK
Photo : Hawaii -> cannot scan back
Photo : New York State -> cannot scan front
Photo : Texas ->  OK
Photo : Texas (vertical) ->  cannot scan back
Photo : Washington ->  cannot scan back
Photo : Washington (vertical) ->  cannot scan front

### Environment Details

**BlinkID version:** 
5.9.0

**Device model:** 
Samsung S8

**Device Android version:**
Android Pie 9.0

### Additional information

Can we please have some visibility on why not all USDL are supported.

**Comment by mparadina** [comment]
Hi @damienlo 

Thank you for waiting for our response.

Just to double-check, regarding the term 'photo', are you scanning images of real documents or images from the internet?
Are you scanning them from a monitor screen?

Also, would you mind giving us more details regarding the issues when scanning the documents?
In cases where you can not scan the front/backside of documents, do you get any certain alerts? 
For instance, the "Document not supported" alert?

Regards,
Milan

**Comment by damienlo** [comment]
Hi @mparadina 

> regarding the term 'photo', are you scanning images of real documents or images from the internet?

By photo I kind of mean both. 
For some states we have photo of real documents and for some others we simply have internet images of them

> Are you scanning them from a monitor screen? 

Yes

> In cases where you can not scan the front/backside of documents, do you get any certain alerts? 
I've been running all the test on our integrated version of blink. it's based on "BlinkId-CustomCombinedSample" project of yours.
When I say **cannot scan front**  it means that `MetadataCallbacks().setFirstSideRecognitionCallback` was never called
When I say **cannot scan back** it means that `setFirstSideRecognitionCallback` was called successfully, but then `onScanningDone(scanResult: RecognitionSuccessType)` was not called

Let me know if you need more info or if I should run some more specific tests on my end.

Regards,
Damien

**Comment by mparadina** [comment]
Hi @damienlo 

Thank you for the detailed response.

Regarding the images, I strongly recommend trying out, if possible, to test the SDK on real samples since it is trained on real documents.
The samples found on the internet can sometimes be in an invalid format or have some misplaced information when comparing it to the real document or could have some pieces of information missing.

Also, scanning from a monitor screen can also sometimes cause the scanning process for the SDK to be rather difficult when trying to extract the information from the document, since the screen can produce [the Moire pattern](https://mathworld.wolfram.com/MoirePattern.html).

When you tried to scan real documents, was the scanning process successful?

Regards,
Milan

**Comment by anjapenic** [comment]
Hello @damienlo,

Just wanted to make a quick follow-up here. 

Have you tried scanning real documents? If so, have you experienced further issues with them?

Best regards,
Anja
