### ISSUE TITLE
Non Latin characters

### ISSUE THREAD

**Issue by souheib93** [BlinkID/blinkid-android#242]
Hello,

is there a way to filter non latin characters documents that is being scanned  ? 

Best,
Souheib

**Comment by anjapenic** [comment]
Hello @souheib93,

Which non-latin characters are you reffering to?

Also, which documents, that contain the mentioned non-latin characters, are you trying to scan?

We don't support non-latin characters at the moment, other than the Arabic numeral system, however, we can check if the mentioned non-latin characters you’re interested in are on our roadmap and let you know if we’ll support them in the future.

Regards,
Anja

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
