### ISSUE TITLE
Getting nulls when trying to scan Document with BlinkID-aMinimalSample

### ISSUE THREAD

**Issue by radimmotycka** [BlinkID/blinkid-android#244]
Pls guys would you advise?
I am scanning my Passport with BlinkID-aMinimalSample getting to onScanSuccess but all images are null :(
Would you pls advise?

Pls see attachement.

<img width="1413" alt="Screen Shot 2021-03-25 at 5 54 15 PM" src="https://user-images.githubusercontent.com/65539674/112512529-c03f1280-8d93-11eb-8186-13cc89aeb09e.png">

**Comment by anjapenic** [comment]
Hello @radimmotycka,

After initializing the recognizer, have you set the setReturnFullDocumentImage and setReturnFaceImage to true? If not, here's how to do it:
```
recognizer = new BlinkIdCombinedRecognizer();
recognizer.setReturnFullDocumentImage(true);
recognizer.setReturnFaceImage(true);
```

Please try it out and let us know if it helped!

Regards,
Anja

**Comment by anjapenic** [comment]
Hello @radimmotycka,

Just wanted to make a quick follow-up here.

Have you tried the solution we've provided? Did you find it solved the issue you were experiencing? 

Best regards,
Anja
