### ISSUE TITLE
No virtual method areCameraPixelsLandscapeLeft()Z in class Lcom/microblink/view/BaseCameraView;

### ISSUE THREAD

**Issue by Dhiraj-kumar-kumawat** [BlinkID/blinkid-android#246]
BlinkID version:5.10.0

### Description
![Capture](https://user-images.githubusercontent.com/18437101/114491089-9c088000-9c33-11eb-94d9-922ef745000a.PNG)

I have implemented the below dependencies and found the same BaseCameraView class in multiple dependencies.

implementation('com.microblink:blinkid:5.10.0@aar') {
        transitive = true
    }

    implementation project(':LibBlinkReceiptCamera')
    implementation project(':LibBlinkReceiptCore')
    implementation project(':LibBlinkReceiptRecognizer')

![Error](https://user-images.githubusercontent.com/18437101/114491536-64e69e80-9c34-11eb-9f06-11001ed2221d.PNG)

I want to implement both License scanner and Receipt Scanner but I got an error when I click on scan receipt. I got this error(No virtual method areCameraPixelsLandscapeLeft()Z in class Lcom/microblink/view/BaseCameraView;). So please suggest to me what is the solution to this problem. Thanks.

**Comment by anjapenic** [comment]
Hello @Dhiraj-kumar-kumawat,

It is currently not possible to combine both BlinkID and BlinkReceipt in one app. We are aware of the issue and are working towards making it possible in BlinkID v6 which is scheduled for release this summer. 

We will make sure to reach out when it's released.

Best regards,
Anja

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
