### ISSUE TITLE
Got ANR when call method terminate(),when the network is not very well.

### ISSUE THREAD

**Issue by Lijing11** [BlinkID/blinkid-android#249]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

Issue description goes here.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:**

**Device model:**

**Device Android version:**

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by anjapenic** [comment]
Hi @Lijing11,

Could you please share a bit more info on when does this happen, which SDK version are you using, and on which device is it occurring? 

Best regards,
Anja

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
