### ISSUE TITLE
Network error on startup

### ISSUE THREAD

**Issue by g522811** [BlinkID/blinkid-android#252]
Before opening an issue, check that you are using the latest version of the BlinkID SDK.

Also, make sure your issue isn't on [the list of common problems.](https://github.com/BlinkID/blinkid-android#-frequently-asked-questions-and-known-problems)

---

### Description

I'm integrating BlinkID into an Android app by following the [README here](https://github.com/BlinkID/blinkid-android). I'm able to successfully grab a license but upon scanning startup I get a popup dialog simply stating "Network error" with only one option to close the dialogue which also kills the scanning activity. I can see the scanning activity running in the background but it's not successfully providing any feedback when placing a drivers license in frame.

Please try to provide steps to reproduce the issue, or minimal code sample. It will help us resolve the issue faster.

### Environment Details

**BlinkID version:** 5.12.0

**Device model:** samsung Galaxy S7 (SM-G930T)

**Device Android version:** 8.0.0

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

**Comment by anjapenic** [comment]
Hello @g522811,

Could you please try adding to `AndroidManifest.xml`​ both of these permissions:

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

```

Let us know if it helped!

Best regards,

Anja

**Comment by g522811** [comment]
@anjapenic that was 100% my issue. Closing out the ticket. Maybe consider mentioning this in the README? Would've saved me much frustration! :)
