### ISSUE TITLE
Capture preview gets stretched on Samsung Active Tab2 - SM-T395 & Samsung A50 - SM-A505FN 

### ISSUE THREAD

**Issue by mariasenosiain** [BlinkID/blinkid-android#255]
### Description
Capture preview gets stretched on Samsung Active Tab2 - SM-T395 & Samsung A50 - SM-A505FN, also images returned by the library are stretched. Seems like aspect ration is broken on these devices.
I've checked your [release notes for 5.13.0](https://github.com/BlinkID/blinkid-android/releases/tag/v5.13.0) and there is a mention about a fix for Active Tab2, but not sure if you had included the device model **SM-T395** , because it is still failing for that one. 
Also, recently we've detected same issue in Samsung A50 - SM-A505FN.

At the moment we have fixed it forcing legacy camera usage for both devices by calling: `blinkRecognizerView.setForceUseLegacyCamera(true)`   

But it would be good to have it fixed in the library :)
### Environment Details

**BlinkID version:** 5.13.0

**Device model:** 
- Samsung Galaxy Tab Active2 - SM-T395
- Samsung A50 - SM-A505FN 

**Device Android version:** Android 9

**Device ABI (processor architecture, e.g. ARMv7):** armeabi-v7a

### Log file

Attached: [BlinkID_logcat.log](https://github.com/BlinkID/blinkid-android/files/7117093/BlinkID_logcat.log)

### Additional information

Here a couple of screenshots from Samsung Galaxy Tab Active2 - SM-T395:

## Preview stretched ❌
![preview_wrong](https://user-images.githubusercontent.com/33830959/132245269-458a27fb-0b70-417b-b97f-724a7a63c797.png)

## Preview forcing legacy camera usage ✅

![preview_fine](https://user-images.githubusercontent.com/33830959/132245275-99be440d-a6f7-4392-95f3-6096ed88b42f.png)

**Comment by anjapenic** [comment]
Hello @mariasenosiain,

Thanks for letting us know and sharing the screenshots, glad to hear you've managed to implement the workaround by forcing camera legacy. We've forwarded this internally and will make sure that the next release includes a fix for the devices you've reported.

Let us know if there's anything we could help with further :)

Best regards,

Anja

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
