### ISSUE TITLE
UI customisation

### ISSUE THREAD

**Issue by shikha1992** [BlinkID/blinkid-android#256]
I want to customize the screen. Have to remove flash icon at top and progress bar at middle of screen.
Can you please help with that 

### Environment Details

**BlinkID version:**com.microblink:blinkid:5.13.0@aar

**Device model:** One plus 7 pro

**Device Android version:** 10

**Device ABI (processor architecture, e.g. ARMv7):**

**Comment by culoi** [comment]
Hello @shikha1992 

Please check out our Sample folder and [CustomUI ](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-CustomUISample)sample for the customization of the UI in the BlinkID. 

Also, the relevant article can be found here: https://github.com/BlinkID/blinkid-android#-custom-ux-with-recognizerrunnerview

Hope it helps.

Regards,

Ivan

**Comment by shikha1992** [comment]
I picked Custom-Combined Sample from SampleApp. 
I am able to customise the screen but on scan result is empty. No data. 

`BlinkIdCombinedRecognizer.Result result = mRecognizer.getResult();
            if (result.getResultState() == Recognizer.Result.State.Valid) {}`

here result status returned is valid but when trying to get data from result its empty. Can you please help with that
