### ISSUE TITLE
Korean ID Card Information Extraction

### ISSUE THREAD

**Issue by hassammughal** [BlinkID/blinkid-android#259]
There is not enough information being extracted from Korean ID Card. The good thing was that it does hide the Registration Number, but it doesn't extract the other information such as Name, Address, Date of expiry. In addition the registration number should be shown like this: 920301-4****** in the personal number field.

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
