### ISSUE TITLE
cordova build android fails

### ISSUE THREAD

**Issue by francislagares** [BlinkID/blinkid-android#263]
### Description

After upgrading to v5.15.0 cannot generate apk.

1. cordova prepare android
2. cordova build android

Throws me: 

> Task :app:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     /home/user/.gradle/caches/transforms-2/files-2.1/42f4abcd1335f10590e79520ce40d264/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.

### Environment Details

**BlinkID version: 5.15.0

**Device model: Android

**NodeJS: v16.30.0

**NPM: 8.3.0

**Comment by mparadina** [comment]
Hi @francislagares 

The mentioned issue could be connected with the `targetSdkVersion`
You can try placing the target SDK version to 31.

In your Cordova project, you can change this by going to the `config.xml` file.
After the line `<platform name="android">`, you can add:
`<preference name="android-targetSdkVersion" value="31" />`

Let me know if this helped.

**Comment by francislagares** [comment]
Hi @mparadina

Well I just did what you suggested, now I get another one:

> Task :app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve androidx.core:core:1.6.+.
     Required by:
         project :app
      > Failed to list versions for androidx.core:core.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/androidx/core/core/maven-metadata.xml.
            > Could not get resource 'https://jcenter.bintray.com/androidx/core/core/maven-metadata.xml'.
               > Could not GET 'https://jcenter.bintray.com/androidx/core/core/maven-metadata.xml'.
                  > Read timed out

**Comment by premedios-i9** [comment]
@francislagares install android with the following command:

`cordova platform add android@10`

with that, you get no errors on build. problem solved.

**Comment by krizaa** [comment]
This issue was closed because it has been inactive for such a long time. If the issue persists, please open a new one.
