### ISSUE TITLE
Expose `com.microblink.view.recognition.DetectionStatus`

### ISSUE THREAD

**Issue by Sevastyan** [BlinkID/blinkid-android#270]
### Description

I am using a direct API for recognition and want to get callbacks with `com.microblink.view.recognition.DetectionStatus`. This is not possible at the moment.

Please, expose it.

**Comment by anjapenic** [comment]
Hi @Sevastyan,

The [DetetectionStatus](http://blinkid.github.io/blinkid-android/com/microblink/view/recognition/DetectionStatus.html) is used with live camera scanning and can't be used when sending pictures to DirectAPI. Could you share with us what exactly would you like to detect so we could check if there's another solution we could suggest?

Best regards,
Anja

**Comment by Sevastyan** [comment]
@anjapenic Thank you for a prompt response. I aim to develop a typical universal document scanner (using combined `BlinkIdCombinedRecognizer`, expected documents will be passports, ID cards, drivers licenses and visas) and want to have a bit more live feedback for the user. You already expose `onGlare` callback, so why there is no callback for `DetectionStatus`, which seems to be from the same category of a live feedback (`CAMERA_AT_ANGLE`, `CAMERA_TOO_NEAR`, etc.)?

**Comment by anjapenic** [comment]
Hi @Sevastyan,

You can check `[RecognitionSuccessType](https://blinkid.github.io/blinkid-android/com/microblink/recognition/RecognitionSuccessType.html)` and `[ProcessingStatus](https://blinkid.github.io/blinkid-android/com/microblink/entities/recognizers/blinkid/generic/ProcessingStatus.html)` if that works for you. As stated above, DetectionStatus is used when SDK is detecting documents during live scanning and can't be used when processing static images via DirectAPI.

Best regards,
Anja

**Comment by Sevastyan** [comment]
@anjapenic I don't think you understand my question. Why there is `onGlare` callback and no callback for "camera too near" situation? Semantically, these two are of the same category and I think `MetadataCallbacks` should contain the same information as `DetectionStatus` provides. Otherwise, you are forcing developers to use your solution with your own camera imagery management, undermining your own "Direct API" in terms of features. If there is a concrete technical reason that makes reporting `DetectionStatus` via `MetadataCallbacks` impossible, I'd like to hear it. But I doubt there is one, hence my inquiry.

All in all, it seems to me, that API is a bit random and needs consolation across "Direct API" and out-of-the-box solution with Android Activities and Fragments.
