### ISSUE TITLE
Camera view has no children?!?

### ISSUE THREAD

**Issue by Sevastyan** [BlinkID/blinkid-android#272]
### Description

I'm tying to use `RecognizerRunnerView` with custom `LifecycleOwner`, but there is no camera preview (just a white screen) and the following message:

```
E/RecognizerRunnerView.java:4@main(10487): Camera view has no children?!?
```

What is wrong?

**Comment by anjapenic** [comment]
Hi @Sevastyan,

Could you please give us a bit more info on how you've implemented RecognizerRunnerView into scan activity?

Regards,
Anja
