### ISSUE TITLE
How to change to front-facing camera using `RecognizerRunnerView`?

### ISSUE THREAD

**Issue by Sevastyan** [BlinkID/blinkid-android#273]

**Comment by anjapenic** [comment]
Hi @Sevastyan,

Use [http://blinkid.github.io/blinkid-android/com/microblink/view/recognition/RecognizerRunnerView.html#prepareCameraSettings(com.microblink.hardware.camera.CameraSettings)](http://blinkid.github.io/blinkid-android/com/microblink/view/recognition/RecognizerRunnerView.html#prepareCameraSettings(com.microblink.hardware.camera.CameraSettings)) to prepare CameraSettings and [set CameraType](http://blinkid.github.io/blinkid-android/com/microblink/view/BaseCameraView.html#setCameraType(com.microblink.hardware.camera.CameraType)) to [CAMERA_FRONTFACE](http://blinkid.github.io/blinkid-android/com/microblink/hardware/camera/CameraType.html#CAMERA_FRONTFACE).

Regards,
Anja

**Comment by Sevastyan** [comment]
@anjapenic But that method is `protected` and `RecognizerRunnerView` is `final`. How do I call it?

**Comment by anjapenic** [comment]
@Sevastyan you can use this method - http://blinkid.github.io/blinkid-android/com/microblink/view/BaseCameraView.html#setCameraType(com.microblink.hardware.camera.CameraType)
