### ISSUE TITLE
Manual Focus

### ISSUE THREAD

**Issue by zarulizham** [BlinkID/blinkid-android#29]
Is there any way to make the camera manual focus by setting the focus value instead of auto focus?

**Comment by DoDoENT** [comment]
Hi @zarulizham,

with builtin camera management you cannot use the manual camera focus, however, you can create your own camera management and use DirectAPI for processing camera frames, as shown in [this example](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDirectApiDemo).

**Comment by zarulizham** [comment]
That's great. Thank you!
