### ISSUE TITLE
setNumMsBeforeTimeout before partial

### ISSUE THREAD

**Issue by mvayngrib** [BlinkID/blinkid-android#31]
first of all, great library guys!

the issue i was having is that I was using ScanCard expecting it to come to onActivityResult after the timeout, but it didn't. The docs clarified things: "...number of miliseconds that must pass after first partial scan result has arrived before scan activity triggers a timeout."

Is there a way to trigger a timeout for ScanCard whether or not there is a partial result? Or somehow programmatically cancel the scanning process?

thanks!

**Comment by DoDoENT** [comment]
Hi!

There is no way to set hard timeout on ScanCard activity. However, you can create your [custom scan activity](https://github.com/BlinkID/blinkid-android#recognizerView) (see [example](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDemoCustomUI)), where you can control timeout as you wish.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional question
