### ISSUE TITLE
Hide focus rectangle doesn't seem to work

### ISSUE THREAD

**Issue by arazinger** [BlinkID/blinkid-android#33]
I'm using ScanCard activity with ScanCard.EXTRAS_SHOW_FOCUS_RECTANGLE extra set to "false", but when activity starts, focus rectangle is still displayed.

**Comment by DoDoENT** [comment]
Does the rectangle you see have round or sharp edges?

Focus rectangle always has sharp edges and displays the location where camera is focuing on. On the other hand, ScanCard activity displays rounded-corner rectangle which shows user where ID document should be positioned for performing the scanning.

**Comment by arazinger** [comment]
It has rounded corners. I tought this represents the focus rectangle.
So there is no way to hide this "positioning" rectangle when using ScanCard activity?

**Comment by DoDoENT** [comment]
The whole point of ScanCard activity is in displaying this "positioning" rectangle. If you want custom scan UI, you should [embed RecognizerView into your scanning activity](https://github.com/BlinkID/blinkid-android#recognizerView).

**Comment by arazinger** [comment]
Thanks for info.
