### ISSUE TITLE
Touch to focus

### ISSUE THREAD

**Issue by wedjohn57** [BlinkID/blinkid-android#4]
The autofocus is very slow. Suggest to add "touch to focus" instead.

Device tested: Nexus 6P
Step to reproduce:
1. open the camera view
2. point it at a far object
3. point camera to the scan object
4. auto focus take like more than 10 seconds to change the focus.

While scanning is fast if i point the camera to near object first before i start camera view. which is not the case for many user.

**Comment by DoDoENT** [comment]
Hi,

thanks for reporting. This may be a device issue. You can test this with our [Direct API custom camera demo](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDirectApiDemo/src/main/java/com/microblink/blinkid/demo/customcamera/camera2). This demo uses minimal camera management from android examples. If focus is equally slow in that example, then it is a device-specific issue.

Best regards!

**Comment by wedjohn57** [comment]
Thanks for the fast response. Yes, I think you are right. It is working perfectly on samsung note 5 & samsung s4. 

Anyway, did you verified the library to work on any android 6.0 device?

**Comment by DoDoENT** [comment]
Yes, we tested the library on Android 6.0 with Nexus 5X, Nexus 6, HTC One M8 and Samsung Galaxy S6. We needed to do that to add support for new runtime camera permissions that were introduced with Android 6.0.

**Comment by wedjohn57** [comment]
Ok thanks. Great if you can test it with Nexus 6P as well.
