### ISSUE TITLE
How to scan front and back side of Pakistan CNIC

### ISSUE THREAD

**Issue by Shahjahan786** [BlinkID/blinkid-android#40]

**Comment by culoi** [comment]
Hello @Shahjahan786 

Can you please share the sample of Pakistan CNIC? 

Regards,

Ivan

**Comment by Shahjahan786** [comment]
![front](https://cloud.githubusercontent.com/assets/5007881/26489068/4d115d40-421f-11e7-99fc-c7c4f23ef22b.JPG)
![back](https://cloud.githubusercontent.com/assets/5007881/26489067/4d0e50aa-421f-11e7-95b7-9362babf882f.JPG)

**Comment by Shahjahan786** [comment]
![image](https://cloud.githubusercontent.com/assets/5007881/26489323/5f69aa1e-4220-11e7-8b5a-0e9bcf36b2b6.png)

**Comment by culoi** [comment]
Hello @Shahjahan786 

On this ID is quite hard to do OCR due to the background of the card. The green pattern will definitely interfere with the font. 

Does ID card contain barcode or QR code on the back side? 

Regards,
Ivan

**Comment by Shahjahan786** [comment]
Yes it contains, there are two formats one is with barcode and other one
with qr

**Comment by culoi** [comment]
Ok,

Can you please share back side of the document? 
The solution is to use document detector to capture front side of the ID and then PDF417 or QR recognizer to extract the data. On that way, you will get an image of the document + all the data that are contained in the barcode. 

Regards,

Ivan

**Comment by Cerovec** [comment]
Hi @Shahjahan786,

do you have any update on this issue?
Can you please share the back side of the document?

Thanks,
Jurica.

**Comment by Shahjahan786** [comment]
Below image contains both above the front and below is the back side

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional question

**Comment by asadkhan809066-lgtm** [comment]
Y
