### ISSUE TITLE
E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found

### ISSUE THREAD

**Issue by CattleOfRa** [BlinkID/blinkid-android#42]
I am currently getting the following error:

E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found

After enabling setDebugImageMetadataSettings to debug why OCR not reading Card properly on Android,

The full code for MetadataSettings and MetadataSettings.ImageMetadataSettings.DebugImageMetadataSettings is as follows:

```
MetadataSettings.ImageMetadataSettings.DebugImageMetadataSettings dims = new MetadataSettings.ImageMetadataSettings.DebugImageMetadataSettings();
dims.setAll(true);

MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();
ims.setDewarpedImageEnabled(true);
ims.setSuccessfulScanFrameEnabled(false);
ims.setDebugImageMetadataSettings(dims);
```

I am currently testing under the following environment:

> OS name: Android
OS version: 7.0
Model: Lenovo P2a42

**Comment by DoDoENT** [comment]
Hi!

Does your app crash after printing that error or it simply ignores it and continues to work? Our recognition code does not use in any way `libwvm.so`, however after some research I've found that it is being indirectly used by audio player. Our ScanActivity plays a "beep" sound on successful scanning and on your device the audio subsystem might be broken ([googling](https://www.google.hr/search?q=Failed+to+open+libwvm.so%3A+dlopen+failed%3A+library+%22libwvm.so%22+not+found&oq=Failed+to+open+libwvm.so%3A+dlopen+failed%3A+library+%22libwvm.so%22+not+found&aqs=chrome..69i57j69i61.195j0j4&sourceid=chrome&ie=UTF-8) for this error reveals that lots of apps are suffering from it on some devices).

You can disable the "beep" sound by sending invalid resource ID (such as `-1`) [to ScanActivity](https://github.com/BlinkID/blinkid-android#intent_EXTRAS_BEEP_RESOURCE) or by creating your own scan activity according to [documentation](https://github.com/BlinkID/blinkid-android#recognizerView) and [example](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDemoCustomUI).

**Comment by ITDreamSKY** [comment]
I still don't know how to solve

**Comment by shekharartemedia** [comment]
hi i am gettinig the same issue. please help me

**Comment by i1E** [comment]
Hi @shekharartemedia, which version of the SDK you are using? Can you please share the full log output and stack trace?

**Comment by shekharartemedia** [comment]
@i1E i am using sdk 26. i am getting this bug is only for "lava Z80"  when i open the gallery from custom camera.
 here is mu code to open the gallery 

Intent intent = new Intent(Intent.ACTION_VIEW);
        intent.setType("image/*");

        intent.addFlags(Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        intent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION);
        startActivity(intent);

**Comment by i1E** [comment]
Hi @shekharartemedia, what do you mean by "custom camera"? It seems that this error is not related to our SDK. We still need full stack trace and more information from the log output.

**Comment by shekharartemedia** [comment]
I have create my custom camera where user can click his/her photos and i am adding the watermarking on the image and save it to gallery.But when i click on gallery button then screen is hang.
