### ISSUE TITLE
Did BlinkID support Xamarin

### ISSUE THREAD

**Issue by hnieef** [BlinkID/blinkid-android#44]
hi . i developing using xamarin for android
did blinkid for android can use using xamarin
hope can hear you soon
thank you

**Comment by DoDoENT** [comment]
Hi! Please check [BlinkID for Xamarin SDK](https://github.com/BlinkID/blinkid-xamarin).

**Comment by Cerovec** [comment]
Hi @hnieef - please close the issue if you found what you were looking for.
