### ISSUE TITLE
Edit Layout of SegmentScan Activity

### ISSUE THREAD

**Issue by ZaidWaseem10** [BlinkID/blinkid-android#45]
I love the this tool and I'm building an app around it, but I tried to find a way to edit the layout of the Segment Scan Activity and I couldn't figure it out! 
Looking forward to your help.

**Comment by DoDoENT** [comment]
[Here is the demo app](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDemoCustomSegmentScan) which shows how you can create your own version of SegmentScanActivity. Please take a look.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional question
