### ISSUE TITLE
What is the license of the library?

### ISSUE THREAD

**Issue by ProgFelipe** [BlinkID/blinkid-android#48]
I  couldnt see the license of this library, maybe now I`m blind?

**Comment by DoDoENT** [comment]
The license is commercial.

From README:

> Using BlinkID in your app requires a valid license key. You can obtain a trial license key by registering to Microblink dashboard. After registering, you will be able to generate a license key for your app. License key is bound to package name of your app, so please make sure you enter the correct package name when asked.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional question
