### ISSUE TITLE
BarDecoderRecognizerSettings with setShowFullDocument

### ISSUE THREAD

**Issue by wedjohn57** [BlinkID/blinkid-android#5]
Isn't possible to have barcode image returned for one dimensional scanning?

**Comment by DoDoENT** [comment]
You can subscribe to receiving [video frame that was used for decoding barcode](https://blinkid.github.io/blinkid-android/com/microblink/metadata/MetadataSettings.ImageMetadataSettings.html#setSuccessfulScanFrameEnabled-boolean-) and also to [detection location](https://blinkid.github.io/blinkid-android/com/microblink/metadata/MetadataSettings.html#setDetectionMetadataAllowed-boolean-). This combination will ensure you will get both location of barcode in image and the image containing the barcode.

**Comment by DoDoENT** [comment]
Hi @wedjohn57,

is your problem solved? Can we close the issue?

**Comment by wedjohn57** [comment]
Yes. You may close it.
