### ISSUE TITLE
Set up blink Recognizer with RegexParserSettings

### ISSUE THREAD

**Issue by LukeEdghar** [BlinkID/blinkid-android#54]
I am trying to scan an image taken from resources using a Recognizer with a RegerParserSettings inside a fragment. The problem is that **`BaseRecognitionResult `obtained through the callback `onScanningDone` is always null.** I have tried to set up the RecognitionSettings with `MRTDRecognizer` and worked fine, so I think that the library is properly integrated. This is the source code that I am using:
```

@Override
    public void onAttach(Context context) {
        ...

        try {
            mRecognizer = Recognizer.getSingletonInstance();
            mRecognizer.setLicenseKey(context, LICENSE_KEY);
        } catch (FeatureNotSupportedException | InvalidLicenceKeyException e) {
            Log.d(TAG, e.getMessage());
        }
        buildRecognitionSettings();
        mRecognizer.initialize(context, mRecognitionSettings, new DirectApiErrorListener() {
            @Override
            public void onRecognizerError(Throwable t) {
                //Handle exception

            }
        });
    }
```
```
private void buildRecognitionSettings() {
        mRecognitionSettings = new RecognitionSettings();
        mRecognitionSettings.setRecognizerSettingsArray(setupSettingsArray());
    }
```

```
private RecognizerSettings[] setupSettingsArray() {
        RegexParserSettings regexParserSettings = new RegexParserSettings("[A-Z0-9]{17}");
        BlinkOCRRecognizerSettings sett = new BlinkOCRRecognizerSettings();
        sett.addParser("myRegexParser", regexParserSettings);
        return new RecognizerSettings[] { sett };
    }
```

I scan the image like:
`mRecognizer.recognizeBitmap(bitmap, Orientation.ORIENTATION_PORTRAIT, FragMicoblink.this);`

And this is the callback handled in the fragment

```
@Override
    public void onScanningDone(RecognitionResults results) {
        BaseRecognitionResult[] dataArray = results.getRecognitionResults();
        
        //dataArray is null
        
        for(BaseRecognitionResult baseResult : dataArray) {
            if (baseResult instanceof BlinkOCRRecognitionResult) {
                BlinkOCRRecognitionResult result = (BlinkOCRRecognitionResult) baseResult;
                if (result.isValid() && !result.isEmpty()) {
                    String parsedAmount = result.getParsedResult("myRegexParser");
                    if (parsedAmount != null && !parsedAmount.isEmpty()) {
                        Log.d(TAG, "Result: " + parsedAmount);
                    }
                }
            }
        }
    }`

Thanks in advance!

**Comment by DoDoENT** [comment]
If data array is null, then nothing was scanned. Are you sure you are sending the correct orientation of bitmap? Your code reports bitmap in orientation portrait, i.e. as if the bitmap was taken with device camera while device being in portrait mode (i.e. the text lines are vertical and start at the bottom of the image and end at the top). If the bitmap image you are scanning has _normal_ orientation (i.e. text lines are horizontal and text starts from the left and ends on the right - just like in web page), then you should pass LANDSCAPE_RIGHT orientation.

**Comment by LukeEdghar** [comment]
Thanks for your response. You are right, I am taking a photo with the camera and I am placing it in an ImageView to check the orientation. Image has a number horizontally aligned from displayed from left to right (when I place this image in the ImageView it has the correct orientation). I have tried to configure the orientation in ORIENTATION_LANDSCAPE_RIGHT but it's not working either. What orientation should I use?

**Comment by DoDoENT** [comment]
If ImageView is displaying image correctly, then landscape right is the correct orientation to use. However, it could be possible that OCR of the image was incorrect, so regex parser couldn't match your expression (i.e. it's possible that OCR produced punctuation or spaces inside your word and your regex does not account for that).

You can inspect the raw OCR result with the [getOcrResult](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/templating/TemplatingRecognitionResult.html#getOcrResult-java.lang.String-) and if you know you only expect uppercase letters and digits, you might want to tweak RegexParser's [OCR engine options](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkocr/parser/regex/RegexParserSettings.html#getOcrEngineOptions--) and add only [uppercase letters and digits to whitelist](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkocr/engine/BlinkOCREngineOptions.html#addCharToWhitelist-char-com.microblink.results.ocr.OcrFont-). However, bogus spaces could still appear within your words (though not so often), so you should also tweak your regex to account for that.

**Comment by LukeEdghar** [comment]
Thanks it's working now. The result is not as good as expected, I have tried the sample app of the regex expression and it's much more accurate with the same image. I am setting the SettingsRecognition as you mentioned:
`  private RecognizerSettings[] setupSettingsArray() {
        BlinkOCREngineOptions engineOptions = new BlinkOCREngineOptions();
        // only digits are allowed.
        engineOptions.addAllDigitsToWhitelist(OcrFont.OCR_FONT_ANY);
        engineOptions.setMinimumLineHeight(40);
        engineOptions.setColorDropoutEnabled(true);
       
        RegexParserSettings regexParserSettings = new RegexParserSettings("[0-9]+", engineOptions);
        BlinkOCRRecognizerSettings sett = new BlinkOCRRecognizerSettings();

        sett.addParser("myRegexParser", regexParserSettings);

        return new RecognizerSettings[] { sett };
    }`  

To analyze the results I am looking at the OcrResult but **it gives me lots of 1's and multiple lines for an image with a single line of text**:
`@Override
    public void onScanningDone(RecognitionResults results) {

        BaseRecognitionResult[] dataArray = results.getRecognitionResults();
        // we've enabled only one recognizer, so we expect only one element in dataArray
        Log.d(TAG, "Recognition settings: " + dataArray);
        if(dataArray!= null && dataArray.length == 1){
            if (dataArray[0] instanceof BlinkOCRRecognitionResult) {
                BlinkOCRRecognitionResult result = (BlinkOCRRecognitionResult) dataArray[0];

                if (result.isValid() && !result.isEmpty()) {
                    OcrResult ocrResult = result.getOcrResult();
                    if(ocrResult!= null){
                        Toast.makeText(context, "Result: " + ocrResult.toString(), Toast.LENGTH_LONG).show();
                        Log.d(TAG, "Result raw: " + ocrResult.getBlocks()[0].toString());
                    }
                }
            }
        }`

How can improve the analysis of the data to get a result as good as the obtained in the RegexExample handled in `SegmentScanActivity `?

**Comment by DoDoENT** [comment]
Hi @LukeEdghar.

The difference between your code and SegmentScanActivity is that your code uses DirectAPI, which can process only single bitmap image you send for processing, while SegmentScanActivity processes camera frames as they arrive from the camera. While doing so, it can utilise time redundant information to improve the OCR quality, i.e. it combines consecutive OCR results from multiple video frames to obtain a better quality OCR result.

This feature is not available via DirectAPI - you need to use either SegmentScanActivity, or custom scan activity with [our camera management](https://github.com/BlinkID/blinkid-android#recognizerView).

**Comment by LukeEdghar** [comment]
To help others if they face the same problem. I have notice that if you pass an image with a very high resolution it doesn't recognize the text properly (it makes artifacts). To improve the accuracy it's better to scale down the image.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have questions or contact us directly at support@microblink.com.
