### ISSUE TITLE
How to scan ID Card & Driving License in Indonesia?

### ISSUE THREAD

**Issue by mychaelgo** [BlinkID/blinkid-android#55]
Hi, i wanto to scan ID Card & Driving License in Indonesia, it's supported on sample app in play store (https://play.google.com/store/apps/details?id=com.microblink.blinkidapp) but i see in this blinkid-android sdk on github indonesia not supported yet

Any solution?

**Comment by i1E** [comment]
Hi @mychaelgo, 

Indonesian ID Card and Driver License are not fully supported by the SDK yet, you can use [DocumentFaceRecognizer](https://blinkid.github.io/blinkid-android/index.html) to scan front side of the document and obtain face image and full document image as they are returned in our play store app. To obtain document images you can use [ImageListener](https://github.com/BlinkID/blinkid-android#-using-imagelistener-to-obtain-images-that-are-being-processed).

**Comment by culoi** [comment]
Hello @mychaelgo 

In version 3.13 of the BlinkID SDK for Android: https://github.com/BlinkID/blinkid-android/blob/master/Release%20notes.md#3130 we added support for the front side of the Indonesian ID. Please test it and if you have any additional question, you can reopen the issue or contact us directly at support@microblink.com
