### ISSUE TITLE
Singapore Front ID Scanner issue

### ISSUE THREAD

**Issue by teokw90** [BlinkID/blinkid-android#57]
I had tried to scan Singapore Permanent Residence(SPR) ID and found that first character of Name, DOB and Nationality get chopped off. But this issue does not found in Singapore Citizen ID.

**Comment by culoi** [comment]
Hello @teokw90 

Yes, we just noticed the same issue. Looks like the letters on the PR card are slightly moved to the left compared to the Singapore ID card.

Can you please confirm that only difference between ID and PR card is in color? https://www.quora.com/How-can-I-find-out-if-someone-is-a-PR-holder-of-Singapore

We will fix this in one of our next releases.

Regards,

Ivan

**Comment by teokw90** [comment]
Hello @culoi,

After verification, we found that PR card's profile photo's sizing is different compare to Singapore ID profile photo's sizing. That is the reason why first character of Name, DOB and Nationality get chopped off

**Comment by teokw90** [comment]
Hi Ivan,

version 3.12.0 still not yet fix the Singapore PR ID issue?

Regards,
Kuan Wah Teo

**Comment by culoi** [comment]
This is fixed in the new API version for the blinkid-android. Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
