### ISSUE TITLE
Disable autofocus

### ISSUE THREAD

**Issue by dslak** [BlinkID/blinkid-android#58]
I need to use the ocr reader on a device with no autofocus camera, how can i disable it?
Tnx!

**Comment by i1E** [comment]
Hi @dslak,

for some recognizers, camera with autofocus is required. Which recognizer(s) you are using? Please check [this](https://github.com/BlinkID/blinkid-android#checking-for-blinkid-support-in-your-app) section for more details.

**Comment by dslak** [comment]
Thanks, I had already seen this section, but unfortunately I had to find another solution more suitable for my device (Epson Moverio BT300).

Thanks anyway for the answer.
