### ISSUE TITLE
How can I get the bitmap after scanned ID Document

### ISSUE THREAD

**Issue by longph92** [BlinkID/blinkid-android#6]
I used the function of ID Document in BlinkIdDemo, it's worked perfect. But I want to get the bitmap of card when it's return the result, so how can I do it?
I tried put the Extra_Output in intent but it's not working :(
`
                Intent intent = mElements[position].getScanIntent();
                url = getURL();
                intent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(new File(url)));`

**Comment by i1E** [comment]
Hi longph92,
to get the image, you first have to enable this option in recognizer that you use, for example if you use MRTD recognizer, you should use method [setShowFullDocument](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/MRTDRecognizerSettings.html#setShowFullDocument-boolean-):
```java
 ...
 MRTDRecognizerSettings mrtd = new MRTDRecognizerSettings();
 // set to true to obtain images containing full document
 mrtd.setShowFullDocument(true);
 ...
```
When you are creating the intent for one of the provided scan activities, you have to send the [ImageListener](https://blinkid.github.io/blinkid-android/com/microblink/image/ImageListener.html) and desired [ImageMetadataSettings](https://blinkid.github.io/blinkid-android/com/microblink/metadata/MetadataSettings.ImageMetadataSettings.html):
```java
 Intent intent = new Intent(this, ScanCard.class);
 ...
 MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();
 // sets whether image that was used to obtain valid scanning result will be available
 ims.setSuccessfulScanFrameEnabled(true);
 intent.putExtra(ScanActivity.EXTRAS_IMAGE_METADATA_SETTINGS, ims);
 intent.putExtra(ScanActivity.EXTRAS_IMAGE_LISTENER, new MyImageListener());
 ...
```
You can find more information and an example how to implement [ImageListener](https://blinkid.github.io/blinkid-android/com/microblink/image/ImageListener.html) in our [documentation](https://github.com/BlinkID/blinkid-android#-using-imagelistener-to-obtain-images-that-are-being-processed).

When you obtain the image, you can use [convertToBitmap()](https://blinkid.github.io/blinkid-android/com/microblink/image/Image.html#convertToBitmap--) method to get the bitmap.

**Comment by longph92** [comment]
Hi @i1E ,
It's returned the result but I don't know why the bitmap cannot save to sdcard, it's always throws FileNotFoundException. I had tried many method to save the bitmap but still not work :(. So thank for your answers, it's helpful :+1:

**Comment by longph92** [comment]
Hi @i1E ,
I had found the issue from my device on 6.0, it's denied the permission to write to sdcard. So now I want to crop the card only instead of full image. So it's possible?

**Comment by longph92** [comment]
![](mtp://[usb:003,047]/Phone/blink/MI_lomng.jpg)

**Comment by i1E** [comment]
Hi,
to save bitmap to sdcard, you have to [obtain permissions for external storage](http://developer.android.com/training/basics/data-storage/files.html#GetWritePermission). If you use API level >= 23, working with permissions is described [here](http://developer.android.com/training/permissions/requesting.html).

To get dewarped(cropped) images, you have to enable that option in ImageMetadataSettings by using [setDewarpedImageEnabled](https://blinkid.github.io/blinkid-android/com/microblink/metadata/MetadataSettings.ImageMetadataSettings.html#setDewarpedImageEnabled-boolean-) method.
```java
...
MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();
// sets whether image that was used to obtain valid scanning result will be available
// don't enable this, if you want only dewarped(cropped) images
ims.setSuccessfulScanFrameEnabled(true);
// sets whether dewarped(cropped) image should be available in MetadataListener
ims.setDewarpedImageEnabled(true);
...
```

**Comment by longph92** [comment]
Hi @i1E ,
It's worked perfect, thank you so much. The BlinkID just only support scan German and UK driver's licenses right? Because my project need to scan a French driver's license.

**Comment by i1E** [comment]
Hi @longph92 ,
for now, it is possible to scan German, UK and US driver's licenses with BlinkID SDK. In the future, we plan to support scanning of driver's licenses from other countries, but at this moment we don't know exactly when we will support the French driver's licenses.

Thanks for your interest.

**Comment by DoDoENT** [comment]
Hi @longph92,

currently BlinkID supports only scanning of US Driver's License 2D barcodes, MRZ documents (passports and IDs containing machine readable zone), german and UK driver's licences.

If you could provide us with examples of French driver's licences, we would be happy to add support for them (we do not have any samples, so we cannot add support blindly).

We will not share any private data found on these licenses - the images of licences will only be used to develop data extraction methods needed to add 1st class support for French driver's licences. You can send images of French driver's licences samples to android-devs@microblink.com.

**Comment by DoDoENT** [comment]
Hi @longph92,

can we close this issue?

**Comment by longph92** [comment]
Hi @i1E ,
I'm very interesting with blinkID and now I'm implementing the demo project with scan France and Mexican. So how can I setting for each country? it's means the user can be scan 1 type of card only at the moment.

**Comment by DoDoENT** [comment]
> Hi @i1E ,
> I'm very interesting with blinkID and now I'm implementing the demo project with scan France and Mexican. So how can I setting for each country? it's means the user can be scan 1 type of card only at the moment.

Hi @longph92! French and Mexican IDs and driver's licences are currently not supported out of the box. However, since [v2.6.0](https://github.com/BlinkID/blinkid-android/releases/tag/v2.6.0) we added support for [Templating API](https://github.com/BlinkID/blinkid-android#blinkOCR_templating) which gives you possibility to add support for custom documents. [Here](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo/BlinkIDDemo/src/main/java/com/microblink/util/templating) you can find two examples of how Templating API could be used to add support for Croatian ID cards. You can use the same approach for Mexican and French documents.
