### ISSUE TITLE
MRTD - v3.12.0 - Glare problems

### ISSUE THREAD

**Issue by CattleOfRa** [BlinkID/blinkid-android#60]
Hi all,

I am currently trying to read MRTD from Passport using Microblink v3.12.0 but the Application is crashing everytime with the following error message:

https://paste.ofcode.org/V3fBvzYHnXkGbzhQup5JQ

The code which used to work in previous versions of Microblink is the following

```
private ListElement buildMrtdElement() {
        MRTDRecognizerSettings sett = new MRTDRecognizerSettings();
        sett.setShowFullDocument(true);
        return new ListElement("ID document or Passport", buildIntent(activity, new RecognizerSettings[]{sett}, ScanActivityFront.class, null));
}
```

I have tried playing around with the methods provided bellow but without much success. Tried enabling, disabling, and so on a so forth.

```
private ListElement buildMrtdElement() {
        ...
        sett.setDetectGlare(true);
        sett.setDetectGlare(false);
        sett.shouldDetectGlare();
        ...
}
```

ScanActivityFront.class is a custom class using the Templating API provided by Microblink. Within this class, my metadata settings also sets _setGlareMetadataAllowed_ to _true_:

```
MetadataSettings ms = new MetadataSettings();
ms.setGlareMetadataAllowed(true);
```

Any help with this would be greatly appreciated

**Comment by i1E** [comment]
Hi @CattleOfRa,

we have double checked the latest version of the SDK and it seems that everything works fine with the `MRTDRecognizer`. This crash indicates that you don't have the latest native shared library in your project. Which version of the BlinkID SDK you have used previously? If you are using Eclipse IDE, please check that you have copied the latest native shared libraries to your project, as described [here](https://github.com/BlinkID/blinkid-android#-eclipse-integration-instructions), point number 5.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have questions or contact us directly at support@microblink.com.
