### ISSUE TITLE
How to add animated dots in custom ui?

### ISSUE THREAD

**Issue by barryjohncoronel** [BlinkID/blinkid-android#61]
Hi, how can I add animated dots in my custom scan activity?

**Comment by culoi** [comment]
Hello @barryjohncoronel 

Please follow: https://github.com/BlinkID/blinkid-android#intent_EXTRAS_SHOW_OCR_RESULT_MODE

Regards

**Comment by i1E** [comment]
Hi @barryjohncoronel,

there is an example for adding animated dots when using custom UI integration in [BlinkID-CustomUISample](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-CustomUISample). Please take a look at the [MyScanActivity](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkID-CustomUISample/src/main/java/com/microblink/blinkid/MyScanActivity.java#L101) and check in which way the `OcrResultDotsView` is used for drawing the animated dots.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
