### ISSUE TITLE
Crash in 7.0 devices while scanning(Iam using 3.10.0@aar)

### ISSUE THREAD

**Issue by techvedikasolutions** [BlinkID/blinkid-android#62]
Hi...Im getting crash in android 7.0 nougat version device(Xiaomi Redmi Note 4 and Moto G4).Please find the screen shots of error log.I am unable to scan anything in that device.

Please help me in this issue.
[
![screenshot_2017-10-26-19-43-04-715_com miui bugreport](https://user-images.githubusercontent.com/22232011/32058060-a64be58a-ba86-11e7-9887-06761e0d3ffc.png)
![screenshot_2017-10-26-19-43-09-079_com miui bugreport](https://user-images.githubusercontent.com/22232011/32058061-a69831c4-ba86-11e7-901e-0cbcebb45536.png)

](url)

**Comment by DoDoENT** [comment]
Can you reproduce that crash with our integration demo apps with 3.12.0, or does it happen only in your app?

**Comment by techvedikasolutions** [comment]
Hi,I fixed the issue at my end(due to image saving process app code got crash),upgraded to 3.12.0 and changed all settings related to scanning and changed the image saving process.Now I am able to scan the documents.

Thank you for your assistance.
