### ISSUE TITLE
Documentation for removing unused assets with aapt

### ISSUE THREAD

**Issue by sbaar** [BlinkID/blinkid-android#64]
You might want to consider adding documentation about removing unused assets for use cases that do not use them. We're using blink just to scan usdls, so removing assets for other languages reduced the final apk from 1 mb with this gradle command

```
android {
aaptOptions {
        ignoreAssetsPattern "!model_arabic.zzip:!model_malaysian.zzip:!model_micr.zzip:!model_mrtd.zzip:!model_eudl.zzip:" +
        "!de_address_dictionary.zzip:!de_name_dictionary.zzip:!de_surname_dictionary.zzip:!de_dictionary.zzip:!de_confusions.zzip" +
                ":!de_id_confusions.zzip:!cro_address_dictionary.zzip:!cro_name_dictionary.zzip"
    }
}
```

**Comment by DoDoENT** [comment]
If you don't need those, you can [even further reduce your APK by creating custom build of native binaries](https://github.com/BlinkID/blinkid-android#staticDistrib). The custom build script will not only throw away resources that you don't need - it will create native libraries that will contain only those features that you really need.

**Comment by sbaar** [comment]
Awesome ill look into that
