### ISSUE TITLE
3.12.0 setLicenseKeyTimeLimitedWarningEnabled(false) not working

### ISSUE THREAD

**Issue by axzae** [BlinkID/blinkid-android#67]
I have the following lines of code. but the toast is still showing.

        mRecognizerView = (RecognizerView) findViewById(R.id.recognizerView);
        mRecognizerView.setLicenseKeyTimeLimitedWarningEnabled(false);
        mRecognizerView.create();

**Comment by i1E** [comment]
Hi @axzae,

you can find explanation for this in the [documentation](https://github.com/BlinkID/blinkid-android#-setlicensekeytimelimitedwarningenabledboolean): "To take effect, this method should be called before setting the license key",  which means that you have to call this method before calling mRecognizerView.setLicenseKey("<your_license_key>").

**Comment by axzae** [comment]
thanks i1E! it works! I was only reading the release note hence missing out the important sentence in the documentation.
