### ISSUE TITLE
Malaysian visa ocr

### ISSUE THREAD

**Issue by munnadroid** [BlinkID/blinkid-android#69]
Below is the release notes of 3.13.0:

> added support for Malaysian visa with document code TS - use MRTDRecognizerSettings

Can you please attach sample/demo code for this by using MRTDRecognizerSettings.

**Comment by culoi** [comment]
Hello @munnadroid 

Code for using MRTDRecognizer is the same for all the travel document and can be found here, in our readme file: https://github.com/BlinkID/blinkid-android#-scanning-machine-readable-travel-documents

and here you can find an example of how to get results: https://github.com/BlinkID/blinkid-android#obtaining-results-from-machine-readable-travel-documents-recognizer

Our demo apps are in BlinkIDDemo folder.

https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDDemo

You can build BlinkIDDemo app, and simply select ID document from the menu.

Regards,

Ivan

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
