### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by Rameshkevin** [BlinkID/blinkid-android#7]
I need to scan the PDF417 barcode, when i open the scan activity, the blinkid logo is coming for few seconds then the scan activity is open, i want to remove the blinkid logo. 
I have been tried to remove that icon,  but it automatically generated in each build. Is there  any option to remove or please give me a solution for that.

**Comment by i1E** [comment]
Hi @Rameshkevin,

if you are using provided [ScanCard](https://blinkid.github.io/blinkid-android/com/microblink/activity/ScanCard.html) activity, you can remove splash screen by using [ScanCard.EXTRAS_SPLASH_SCREEN_LAYOUT_RESOURCE](https://github.com/BlinkID/blinkid-android#intent_EXTRAS_SPLASH_SCREEN_LAYOUT_RESOURCE) and provide your own splash overlay layout. For other provided activities, you can do the same thing, but use appropriate extras constant for the activity that you want to use.

**Comment by i1E** [comment]
Hi @Rameshkevin,

can we close the issue if the answer helped?

**Comment by nsdonev** [comment]
Hello @i1E ,
is there easy way to change this in phonegap ?
Thanks .

**Comment by i1E** [comment]
Hi @nsdonev, 

please check [this](https://github.com/BlinkID/blinkid-phonegap/issues/11) issue.

Best regards
