### ISSUE TITLE
Get Image Path

### ISSUE THREAD

**Issue by hongtou820** [BlinkID/blinkid-android#70]
i am testing BlinkIDImageListenerDemo, after i follow u example~
how i get the image path ??
Though ImageListener, i can get image, but cannot pass back to activity

**Comment by hongtou820** [comment]
public class CustomImageListener implements ImageListener {
    private GetImageListener getImageListener;
    public CustomImageListener(GetImageListener getImageListener) {
        this.getImageListener = getImageListener;
    }
    @Override
    public void onImageAvailable(Image image) {
        // we will save images to 'myImages' folder on external storage
        // image filenames will be 'imageType - currentTimestamp.jpg'
        String output = Environment.getExternalStorageDirectory().getAbsolutePath() + "/myImages";
        File f = new File(output);
        if (!f.exists()) {
            f.mkdirs();
        }
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd-HH-mm-ss");
        String dateString = dateFormat.format(new Date());
        String filename = null;
        switch (image.getImageFormat()) {
            case ALPHA_8: {
                filename = output + "/alpha_8 - " + image.getImageName() + " - " + dateString + ".jpg";
                break;
            }
            case BGRA_8888: {
                filename = output + "/bgra - " + image.getImageName() + " - " + dateString + ".jpg";
                break;
            }
            case YUV_NV21: {
                filename = output + "/yuv - " + image.getImageName() + " - " + dateString + ".jpg";
                break;
            }
        }
        Bitmap b = image.convertToBitmap();
        FileOutputStream fos = null;
        try {
            fos = new FileOutputStream(filename);
            boolean success = b.compress(Bitmap.CompressFormat.JPEG, 100, fos);
            if (!success) {
                if (fos != null) {
                    try {
                        fos.close();
                    } catch (IOException ignored) {
                    } finally {
                        fos = null;
                    }
                    new File(filename).delete();
                }
            }
            if(getImageListener!=null) {
                getImageListener.getImagePath(filename);
            }
        } catch (FileNotFoundException e) {
        } finally {
            if (fos != null) {
                try {
                    fos.close();
                } catch (IOException ignored) {
                }
            }
        }
    }

    @Override
    public int describeContents() {
        return 0;
    }
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeParcelable((Parcelable) this.getImageListener, flags);
    }
    protected CustomImageListener(Parcel in) {
        this.getImageListener = in.readParcelable(GetImageListener.class.getClassLoader());
    }
    public static final Creator<CustomImageListener> CREATOR = new Creator<CustomImageListener>() {
        @Override
        public CustomImageListener createFromParcel(Parcel source) {
            return new CustomImageListener(source);
        }
        @Override
        public CustomImageListener[] newArray(int size) {
            return new CustomImageListener[size];
        }
    };

**Comment by i1E** [comment]
Hi @hongtou820, 

in BlinkIDImageListenerDemo, images are stored to external storage, you can modify the source code to achieve what you need. When storing image, you can choose constant path, and in your activity you can later check whether the image exists on that path. Other option is to save images in memory, you can use singleton object, and later you can read images from that singleton.

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional question
