### ISSUE TITLE
How to get face image from myKad

### ISSUE THREAD

**Issue by hockleongloh** [BlinkID/blinkid-android#75]
Hi, I would like to ask is there any method that can directly get the cropped face image from myKad like the one shown in your sample app download from play store? 
Thanks.

**Comment by thetpaingtun93** [comment]
Hi  , you can try DocumentFaceRecognizerSettings as below :

    DocumentFaceRecognizerSettings faceRecognizerSettings = new DocumentFaceRecognizerSettings(DocumentFaceDetectorType.IDENTITY_CARD_TD1);
    faceRecognizerSettings.setShowFaceImage(true);
    
    MyKadFrontSideRecognizerSettings myKad = new MyKadFrontSideRecognizerSettings();
    
    RecognizerSettings[] settArray = new RecognizerSettings[]{myKad,faceRecognizerSettings};
    
    RecognitionSettings settings = new RecognitionSettings();
    settings.setNumMsBeforeTimeout(10000);
    settings.setRecognizerSettingsArray(settArray);
    settings.setAllowMultipleScanResultsOnSingleImage(true);
    
    Intent intent = new Intent(context,ScanCard.class);
    intent.putExtra(ScanActivity.EXTRAS_RECOGNITION_SETTINGS, settings);
    startActivityForResult(intent, REQUEST_CODE);

But sometimes I found that MyKadRecognizer succeeds in scanning first, recognition chain is terminated.

**Comment by hockleongloh** [comment]
Hi,

Isi't the callback is onMetadataAvailable (DocumentFaceRecognitionResult)? 
If yes, how I able to get the byte array or bitmap for the image? 
Thanks.

**Comment by thetpaingtun93** [comment]
Hi, 

If you are using RecognizerView to scan in your app,you can set MetadataListener to RecognizerView and receive Images in MetadataListener. Sample code can be found here => https://github.com/BlinkID/blinkid-android#metadataListener

**Comment by hockleongloh** [comment]
Hi

I'm not using RecognizerView in my project. But if I set DocumentFaceRecognizerSettings in my RecognitionSettings. Which callback and method should I used to get the cropped myKad face image?

**Comment by thetpaingtun93** [comment]
Then you can pass ImageListener in the intent to start the ScanCard Activity like this.

    MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();
    ims.setDewarpedImageEnabled(true);
    
    Intent intent = new Intent(context,ScanCard.class);
    intent.putExtra(ScanCard.EXTRAS_IMAGE_METADATA_SETTINGS, ims);
    intent.putExtra(ScanCard.EXTRAS_IMAGE_LISTENER, imageListener);
    
	//your RecognitionSettings 
    intent.putExtra(ScanCard.EXTRAS_RECOGNITION_SETTINGS, settings);
    
Example implementation of ImageListener can be found here => https://github.com/BlinkID/blinkid-android#imageListener

**Comment by hockleongloh** [comment]
Ok thanks

**Comment by surensth** [comment]
How to get both the face photo and full MyKad image photo ?  I can only get one of them at a time by setting
 either ims.setDewarpedImageEnabled(true);   for facephoto 
  or  ims.setSuccessfulScanFrameEnabled(true); for full image

**Comment by hockleongloh** [comment]
First you need to go to setShowFaceImage(true) for recognizersettings;

Followed by using onImageAvailable listener. Then use image.getImageName to check.

If the name contain .FullDocument then it was full image. Otherwise it was face photo.

**Comment by surensth** [comment]
Thanks @hockleongloh. 
I got it by setting 
setShowFaceImage(true) for recognizersettings;
ims.setDewarpedImageEnabled(true); 
and in imageListener, image.getImageName() 
gave both face and full document photo

**Comment by culoi** [comment]
Hello, with the new API, the image of the face and the document is now returned as the result. This enables much easier integration and image return. You can check our allRecognizerSample demo app: https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID_AllRecognizersSample
