### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by MaheshCapcee** [BlinkID/blinkid-android#8]
i am added a edittext that string value how to scan and validate in Row text

**Comment by DoDoENT** [comment]
Hi!

To quickly start with the scanning, you should check the [quick start instructions with the integration demo app](https://github.com/BlinkID/blinkid-android#quickStart).

To perform simple scanning from your app using BlinkID default scan activity, check [this tutorial](https://github.com/BlinkID/blinkid-android#quickScan).

If you want to integrate scanning feature in your own activity and design custom scanning UI, please check [this article](https://github.com/BlinkID/blinkid-android#recognizerView).

**Comment by Cerovec** [comment]
Please close the issue if the answer helped.
