### ISSUE TITLE
Hide the rectangle in RecognizerView

### ISSUE THREAD

**Issue by zaralockheart** [BlinkID/blinkid-android#81]
I saw from the documentation 
`intent.putExtra(ScanCard.EXTRAS_SHOW_FOCUS_RECTANGLE, true);`

If i use my own `ScanActivity.class` where do I set the boolean for the rectangle?

What I am trying to achieve is to hide the white rectangle in the screen.

Thanks.

**Comment by i1E** [comment]
Hi @zaralockheart,

EXTRAS_SHOW_FOCUS_RECTANGLE intent extra is used to hide focus rectangle which is shown only while camera is focusing. 

It is not possible to hide camera viewfinder in provided ScanCard activity which tells where document should be positioned and whose format is the same as the format of the ID card. I suppose that you mean on that rectangle when you say "white rectangle in the screen".

If you are implementing your own scan activity ([performing custom UI integration](https://github.com/BlinkID/blinkid-android#-embedding-recognizerview-into-custom-scan-activity)), you have full control of the UI.

**Comment by zaralockheart** [comment]
Actually I am implementing my own scan activity

in my xml... I am actually using 
`<com.microblink.view.recognition.RecognizerView
        android:id="@+id/recognizer_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:mb_initialOrientation="portrait"/>`

I wanted to put my own ui for the scanning area, so I think I need to call something to remove 'white reactangle'

**Comment by i1E** [comment]
If you are implementing your own scan activity, then this "white rectangle" does not exist, unless you add it to the layout by yourself. Maybe you have subclassed one of our provided activities, you shouldn't do that. If you want to implement your own scan activity, you should do that from scratch. 

You can find source code example in our [BlinkIDSampleCustomUI](https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkIDSampleCustomUI) sample app. Remove [this](https://github.com/BlinkID/blinkid-android/blob/master/BlinkIDSample/BlinkIDSampleCustomUI/src/main/java/com/microblink/blinkid/demo/customui/MyScanActivity.java#L164) line of code and camera viewfinder (rectangle) will not be added to the layout.

**Comment by zaralockheart** [comment]
thanks!!! apparently that's the line that create the UI.
