### ISSUE TITLE
How do I get image of USDL back side?

### ISSUE THREAD

**Issue by netdur** [BlinkID/blinkid-android#82]
I do combine scan like this

```
USDLCombinedRecognizerSettings usdl = new USDLCombinedRecognizerSettings();
usdl.setReturnFullDocumentImage(true);
usdl.shouldReturnFullDocumentImage();
return usdl;
```

then start intent like this

```
Intent intent = new Intent(context, VerificationFlowActivity.class);
...
MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();
ims.setDewarpedImageEnabled(true);
intent.putExtra(ScanCard.EXTRAS_IMAGE_METADATA_SETTINGS, ims);
intent.putExtra(ScanCard.EXTRAS_IMAGE_LISTENER, new ScanImageListener());
```

in ScanImageListener I check for image `image.getImageName()` to equal `USDLCombinedRecognizerSettings.FULL_DOCUMENT_IMAGE_FRONT` and `USDLCombinedRecognizerSettings.FULL_DOCUMENT_IMAGE_BACK`, however, I cannot find `USDLCombinedRecognizerSettings.FULL_DOCUMENT_IMAGE_BACK` anywhere, how do I get image of back side?

for example, there is `SlovakIDFrontSideRecognizerSettings.FULL_DOCUMENT_IMAGE` and `SlovakIDBackSideRecognizerSettings.FULL_DOCUMENT_IMAGE` but US driving license doesn't have that

**Comment by culoi** [comment]
Hello @netdur 

USDLCombinedRecognizers doesn't return an image of the back side, only results from the PDF417 barcode. 

If you require an image of the back side, then you should create a Custom UI with DocumentDetector, similar that we have implemented in our BlinkID demo app from the PlayStore.

Sample app of the CustomUI can be found in our SDK, under folder BlinkIDSample.

Regards

**Comment by culoi** [comment]
Hello, you are now able to get the image of the front side of the document and result of the PDF417 barcode with our USDLCombined Recognizer. Please check it out in our BlinkIDCustomCombinedSample: https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkID-CustomCombinedSample
