### ISSUE TITLE
ImageMetaData returns rotated bitmap

### ISSUE THREAD

**Issue by iravul** [BlinkID/blinkid-android#85]
After scanning ID or passport, i get image from ImageMetaData.image. It is always 90 Degree rotated bitmap. Then i rotate and crop it with my expectations. That's fine but i want to know is it same for all id types and other scan options? Is it expected result? Or is it possible to get rotation value of image? I want to support all ID types that Microblink supports but first i want to know if i should handle each ID rotation differently or not.

I am using 3.15.1 version.

**Comment by i1E** [comment]
Hi @iravul,

you can check the orientation of the obtained Image by using [Image.getImageOrientation()](https://blinkid.github.io/blinkid-android/com/microblink/image/Image.html#getImageOrientation--) method. Orientation is defined as orientation of the device when the image was taken. Camera frames are always returned as you see them when device orientation is [LANDSCAPE_RIGHT](https://blinkid.github.io/blinkid-android/com/microblink/hardware/orientation/Orientation.html#ORIENTATION_LANDSCAPE_RIGHT), and you should rotate the obtained image based on the orientation of the device when the image was taken, as explained in the [javadoc](https://blinkid.github.io/blinkid-android/com/microblink/image/Image.html#getImageOrientation--).

**Comment by iravul** [comment]
Thank you for detailed answer.
