### ISSUE TITLE
Can we read Place of birth from Passport 

### ISSUE THREAD

**Issue by harishmedamoni** [BlinkID/blinkid-android#86]
Hi Team,

We are using Micro Blink ID version 3.12.0. We are unable to read place of birth from passport.

Can you please let me know whether we can read place of birth from the passport. If it is possible, can you please share me the sample code.

Thanks,
Harish

**Comment by culoi** [comment]
Hi @harishmedamoni 

From the passport, we read information that is written in the MRZ field. 

Unfortunately, MRZ field doesn't contain Place of birth if the MRZ is according to SO/IEC 7501-1 standard.

However, we do have a Templating API solution, which can extract such fields. 

Can you please contact us at support@microblink.com with more information about your use-case.

Regards
