### ISSUE TITLE
Unable to import com.microblink.library.R components in com.microblink.view.viewfinder.viewfindershapeview

### ISSUE THREAD

**Issue by ayushgulati** [BlinkID/blinkid-android#88]
![screen shot 2018-03-14 at 9 47 14 am](https://user-images.githubusercontent.com/17216479/37385789-1acc6f9c-276f-11e8-98f1-76f7b491c547.png)
I am trying to embed your sdk in my android library project

**Comment by i1E** [comment]
Hi @ayushgulati,

there is a problem with resource merging when building your library. Please check [this section](https://github.com/BlinkID/blinkid-android#-ensuring-the-final-app-gets-all-resources-required-by-blinkid) in our documentation.
