### ISSUE TITLE
How to read Full document Image

### ISSUE THREAD

**Issue by harishmedamoni** [BlinkID/blinkid-android#89]
Hi team,

We are using Blink ID 3.12.0 for reading MRZ of UAE emirates ID and passport.
I need to read full document image for both emirates ID and passport.
Can you please help me with the sample code.

Thanks,
Harish

**Comment by culoi** [comment]
Hello @harishmedamoni 

Are you using a mobile camera or you want to upload an image to WEB API? 

If you are using a mobile device, please check out our BlinkIDDemo sample app from the SDK: https://github.com/BlinkID/blinkid-android/tree/master/BlinkIDSample/BlinkIDSample-BlinkIDSample

For the WEB API, you can test it on the following link: www.microblink.com/ws

Regards

**Comment by harishmedamoni** [comment]
Hi,
We are using Blink Id in android mobile.
We are using MRTDCombinedRecognitionResult for reading MRZ  of UAE emirates ID and Passport.

Currently we are using below code to read Face Image and its working fine.
"mrtdCombinedRecognitionResult.getEncodedFaceImage()"

Similarly we see below methods in MRTDCombinedRecognitionResult class
getEncodedFrontFullDocumentImage
getEncodedBackFullDocumentImage

But both are returning null.

Please help.

Thanks,
Harish

**Comment by i1E** [comment]
Hi @harishmedamoni,

you have to enable obtaining of full document images in MRTDCombinedRecognizerSettings by using [setEncodeFullDocumentImag](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/combined/MRTDCombinedRecognizerSettings.html#setEncodeFullDocumentImag-boolean-) method.

**Comment by harishmedamoni** [comment]
Hi,
It is working fine when i use "setEncodeFullDocumentImag" method while reading emirates ID.
In case of scanning emirates ID we are using "MRTDCombinedRecognizerSettings" and able to read front side and back side scanned image.
After scanning result is available as MRTDCombinedRecognitionResult.
so calling below methods
 MRTDCombinedRecognitionResult.getEncodedFrontFullDocumentImage();
 MRTDCombinedRecognitionResult.getEncodedBackFullDocumentImage();

For reading passport we are using "MRTDRecognizerSettings" and able to read result as "RecognitionResults".

I am unable to read document image from RecognitionResults of passport.

Please help


Thanks,
Harish

**Comment by i1E** [comment]
Hi @harishmedamoni,

MRTDRecognizer does not support returning of images through recognition result. You can obtain images as metadata during scan.

## Obtaining images as metadata

When you are creating [MRTDRecognizerSettings](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/mrtd/MRTDRecognizerSettings.html) enable returning of cropped full document image:

```
MRTDRecognizerSettings mrtdRecognizerSett = new MRTDRecognizerSettings();
mrtdRecognizerSett.setShowFullDocument(true);

// pass recognition settings to ScanCard activity
RecognitionSettings settings = new RecognitionSettings();
settings.setRecognizerSettingsArray(new RecognizerSettings[]{mrtdRecognizerSett});
intent.putExtra(ScanCard.EXTRAS_RECOGNITION_SETTINGS, settings);
```

also you have to enable returning of dewarped(cropped) images through metadata in ImageMetadataSettings (because document image is dewarped image):

```
MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();
ims.setDewarpedImageEnabled(true);

// pass image metadata settings to ScanCard activity
intent.putExtra(ScanCard.EXTRAS_IMAGE_METADATA_SETTINGS, ims);

// pass your image listener implementation to VerificationFlowActivity
intent.putExtra(ScanCard.EXTRAS_IMAGE_LISTENER,  new MyImageListenerImplementation());
```

you can find more information about obtaining images with ImageListener [here](https://github.com/BlinkID/blinkid-android#-using-imagelistener-to-obtain-images-that-are-being-processed).

**Comment by harishmedamoni** [comment]
Hi,

I am not able to read image when i am reading MRZ of passport with MRTDRecognizerSettings.

I did the below steps as mentioned

MRTDRecognizerSettings mrtdRecognizerSett = new MRTDRecognizerSettings();
mrtdRecognizerSett.setShowFullDocument(true);

// pass recognition settings to ScanCard activity
RecognitionSettings settings = new RecognitionSettings();
settings.setRecognizerSettingsArray(new RecognizerSettings[]{mrtdRecognizerSett});
intent.putExtra(ScanCard.EXTRAS_RECOGNITION_SETTINGS, settings);


MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();
ims.setDewarpedImageEnabled(true);

// pass image metadata settings to ScanCard activity
intent.putExtra(ScanCard.EXTRAS_IMAGE_METADATA_SETTINGS, ims);

// pass your image listener implementation to VerificationFlowActivity
intent.putExtra(ScanCard.EXTRAS_IMAGE_LISTENER,  new MyImageListenerImplementation());

I set the MetdataListener for my scanning activity and below method is getting called but not able to detect any image.

 public void onMetadataAvailable(Metadata metadata) {
        // This method will be called when metadata becomes available during recognition process.
        // Here, for every metadata type that is allowed through metadata settings,
        // desired actions can be performed.

        // detection metadata contains detection locations
        if (metadata instanceof DetectionMetadata) {
            // detection location is written inside DetectorResult
            DetectorResult detectorResult = ((DetectionMetadata) metadata).getDetectionResult();
            // DetectorResult can be null - this means that detection has failed
            if (detectorResult == null) {
                if (mQvManager != null) {
                    // begin quadrilateral animation to its default position
                    // (internally displays FAIL status)
                    mQvManager.animateQuadToDefaultPosition();
                }
                // when points of interested have been detected (e.g. QR code), this will be returned as PointsDetectorResult
            } else if (detectorResult instanceof QuadDetectorResult) {
                // begin quadrilateral animation to detected quadrilateral
                mQvManager.animateQuadToDetectionPosition((QuadDetectorResult) detectorResult);
            } else if (metadata instanceof ImageMetadata) {
                // report image metadata to imagesetRecognitionSettings  listener
                Image img = ((ImageMetadata) metadata).getImage();
                Bitmap b = img.convertToBitmap();
            }
        }
    }

Please help. Same is working fine for MRTDCombinedRecognizerSettings for UAE Emirates ID.

**Comment by i1E** [comment]
Hi @harishmedamoni,

are you using provided ScanCard activity for scanning, or you have implemented your own scan activity? If you are using ScanCard activity, you should not override `onMetadataAvailable` method, just pass your implementation of `ImageListener`.

```
intent.putExtra(ScanCard.EXTRAS_IMAGE_LISTENER, new MyImageListenerImplementation());
```

Also, you have bug in the attached implementation of `onMetadataAvailable` method:

```
if (metadata instanceof DetectionMetadata) {
        // detection location is written inside DetectorResult
        DetectorResult detectorResult = ((DetectionMetadata) metadata).getDetectionResult();
        // DetectorResult can be null - this means that detection has failed
        if (detectorResult == null) {
            if (mQvManager != null) {
                // begin quadrilateral animation to its default position
                // (internally displays FAIL status)
                mQvManager.animateQuadToDefaultPosition();
            }
            // when points of interested have been detected (e.g. QR code), this will be returned as PointsDetectorResult
        } else if (detectorResult instanceof QuadDetectorResult) {
            // begin quadrilateral animation to detected quadrilateral
            mQvManager.animateQuadToDetectionPosition((QuadDetectorResult) detectorResult);
        } else if (metadata instanceof ImageMetadata) {
            
            // ********************************************************************************************
            // ! this code will never be executed, because if metadata is instanceof DetectionMetadata,
            // ! it is not instanceof ImageMetadata at the same time
           // *********************************************************************************************

            // report image metadata to imagesetRecognitionSettings  listener
            Image img = ((ImageMetadata) metadata).getImage();
            Bitmap b = img.convertToBitmap();
        }
}
```

**Comment by harishmedamoni** [comment]
Hi,

 I rectified the above error. Now onMetadataAvailable is getting called and entering into below condition.

 if (metadata instanceof ImageMetadata) {
            // report image metadata to imagesetRecognitionSettings  listener
            Image img = ((ImageMetadata) metadata).getImage();
            Bitmap b = img.convertToBitmap();
            ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
            b.compress(Bitmap.CompressFormat.PNG, 100, byteArrayOutputStream);
            byte[] byteArray = byteArrayOutputStream .toByteArray();

            //mImageListener.onImageAvailable(img);
        }

But As soon as any image is detected , it is getting called. I want it to be called only after successful scanning of passport. In order to do that what settings i need to use.

Please help.

Thanks,
Harish

**Comment by i1E** [comment]
Hi @harishmedamoni,

if you want to obtain dewarped (cropped) document image, every time when image is detected, `onMetadataAvailable` will be called. You can [clone](https://blinkid.github.io/blinkid-android/com/microblink/image/Image.html#clone--) obtained [`Image`](https://blinkid.github.io/blinkid-android/com/microblink/image/Image.html) and keep reference to the last cloned `Image`, when scanning is done, do something with that `Image`.

If you don't need cropped image, and full camera frame from the successful scan is enough, it is possible to enable returning only full successful camera frames by using `ImageMetadataSettings`(https://blinkid.github.io/blinkid-android/index.html):

```java
MetadataSettings ms = new MetadataSettings();

// ImageMetadataSettings contains settings for defining which images will be returned
MetadataSettings.ImageMetadataSettings ims = new MetadataSettings.ImageMetadataSettings();

// enable returning of image that was used to obtain valid scanning result
ims.setSuccessfulScanFrameEnabled(true)

// set ImageMetadataSettings to MetadataSettings object
ms.setImageMetadataSettings(ims);

mRecognizerView.setMetadataListener(myMetadataListener, ms);

```

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
