### ISSUE TITLE
DetectorRecognizerSettings interferes with default RecognizerSettings

### ISSUE THREAD

**Issue by rachelfong** [BlinkID/blinkid-android#9]
Hi, 

I am currently using this library to scan MRTDs along with some facial features.
However, I realized that once I added the FaceDetectorSettings to the RecognizerSettings array, the onScanningDone method only ever returns results for the FaceDetectorResult and never the MRTDRecognizerResult. I have it setup as below:

````java

        MRTDRecognizerSettings mrtd = new MRTDRecognizerSettings();
        mrtd.setShowFullDocument(true);

        DetectorRecognizerSettings faceDetectorSettings = new DetectorRecognizerSettings(new FaceDetectorSettings(300));
        
        RecognitionSettings recognitionSettings = new RecognitionSettings();
        recognitionSettings.setNumMsBeforeTimeout(5000);
        RecognizerSettings[] settArray = new RecognizerSettings[]{mrtd,,faceDetectorSettings};
        recognitionSettings.setRecognizerSettingsArray(settArray);
        mRecognizerView.setRecognitionSettings(recognitionSettings);
````

My question is, are those two detectors/recognizers meant to be used like that? Without the facial recognition feature, the MRTD scanning works well and returns excellent results but not with FaceDetector in place, it seems that it will never return results for MRTD scanning. 

Any feedback on this would be much appreciated.

**Comment by i1E** [comment]
Hi @rachelfong,

if you want to obtain multiple scan results from the single image, you should use RecognitionSettings method [setAllowMultipleScanResultsOnSingleImage](https://github.com/BlinkID/blinkid-android#setallowmultiplescanresultsonsingleimageboolean). Just add this line of code:

``
recognitionSettings.setAllowMultipleScanResultsOnSingleImage(true)
``

**Comment by rachelfong** [comment]
Hi @i1E,

I shall give that a try. Thank you very much.
