### ISSUE TITLE
Use Templating API for scan document of different size than credit card like Greek for example.

### ISSUE THREAD

**Issue by seintaridis** [BlinkID/blinkid-android#90]
Can I follow this 
https://github.com/BlinkID/blinkid-android/blob/master/templatingAPI/templatingAPI.md
to scan document of different size than credit card like greek documents (Greek ID or other different size documents).
Thanks

**Comment by culoi** [comment]
Hi @seintaridis 

This depends if the ID card is by ISO/IEC 1810 standards ID-1, ID-2, ID-3 type then we can support it. For more info about standards, please follow: https://en.wikipedia.org/wiki/ISO/IEC_7810

If the card is an old type, folded or written with old typing machine, then we don't have option to detect this type of the cards.

Are you able to share a sample of the card that you are trying to support?
You can contact us at support@microblink.com

Regards

**Comment by culoi** [comment]
Closing the issue, please reopen if you have additional questions or contact us directly at support@microblink.com
