### ISSUE TITLE
MyKad address lines

### ISSUE THREAD

**Issue by CattleOfRa** [BlinkID/blinkid-android#92]
I would like to know if there is any way to get the lines of the address in the Malaysian MyKad line by line and segment it into street, postcode, city and state. Currently I am only able to get the whole address as a String.

Thank you for your time.

**Comment by i1E** [comment]
Hi @CattleOfRa,

from the BlinkID v3.7.0, `MyKad` recognizer supports splitting of address to street, ZIP code, city and state. When you obtain `MyKadFrontSideRecognitionResult`, use methods [`getOwnerAddressCity`](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/malaysia/mykad/front/MyKadFrontSideRecognitionResult.html#getOwnerAddressCity--), [`getOwnerAddressState`](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/malaysia/mykad/front/MyKadFrontSideRecognitionResult.html#getOwnerAddressState--), [`getOwnerAddressStreet`](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/malaysia/mykad/front/MyKadFrontSideRecognitionResult.html#getOwnerAddressStreet--) and [`getOwnerAddressZipCode`](https://blinkid.github.io/blinkid-android/com/microblink/recognizers/blinkid/malaysia/mykad/front/MyKadFrontSideRecognitionResult.html#getOwnerAddressZipCode--) to obtain that infromation.
