### ISSUE TITLE
Java plugin not compatible with android plugin.

### ISSUE THREAD

**Issue by mohit-bansal** [BlinkID/blinkid-android#97]
### Description
Cannot sync gradle.
Error: The 'java' plugin has been applied, but it is not compatible with the Android plugins.

Appears as gradle try to sync.

### Environment Details

**BlinkID version:** 3.16.0

**Device model:**

**Device Android version:**

**Device ABI (processor architecture, e.g. ARMv7):**

### Log file

Please enable logging by following instructions [here](https://github.com/BlinkID/blinkid-android#other-problems) and attach full log file.

### Additional information

If there is anything else that you think can help us resolve the issue, write it here.

build.gradle file:

// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}

allprojects {
    repositories {
        jcenter()
        maven { url 'http://maven.microblink.com' }
//        mavenLocal()
        google()
    }
}

// versions of libraries that all modules require

project.ext {
    blinkIdVersion = '3.16.0'
    compileSdkVersion = 27
    targetSdkVersion = 27
    buildToolsVersion = '26.0.2'
    appCompatVersion = '27.1.0'
}

**Comment by mohit-bansal** [comment]
@i1E Firstly, thanks for responding.
As i have mentioned the build.gradle file code above, i have not added anything.
I have not even started any integration.
I just trying to look how the thing works. I just launched it in android studio and this error came.

**Comment by mohit-bansal** [comment]
@i1E  I dont why the error occured. But i redownloaded the project again, no its working fine.

**Comment by i1E** [comment]
Hi @mohit-bansal,

we always test all our sample applications before releasing the new version of the SDK, and everything worked. We checked everything again and didn't find any problems.
