### ISSUE TITLE
Recognition of USDL and US ID card

### ISSUE THREAD

**Issue by epetrenko** [BlinkID/blinkid-android#99]
### Description

Hello there. I need assistance with scanning US ID card / driver license. I tried to scan from both **BlinkID - ID card scanner with OCR** app and **BlinkIDSample** app. And was able to scan both DL and ID card only as images in **BlinkID - ID card scanner with OCR** app. **BlinkIDSample** app didn't scan these types of documents at all. But, for example, German DL and ID has been recognized just fine without any issues. Documentation says that only barcode of USDL can be scanned. I would like to clarify can USDL and USID be recognized somehow in the same way as German or UK DL / ID?

### Environment Details

**BlinkID version:** 3.16.0

**Device model:** Samsung Galaxy Tab S2

**Device Android version:** Android 7.0

**Device ABI (processor architecture, e.g. ARMv7):** arm64-v8a

**Comment by culoi** [comment]
Hi @epetrenko 

Our BlinkID supports scanning both ID an DL from the USA. 

Can you please share from which state did you try to scan DL?
Also, if you are able to share the sample, that would greatly help us to identify the problem. You can share the sample via email: support@microblink.com

Best

**Comment by epetrenko** [comment]
@culoi sorry for a big delay in response.
I have no realm DL example, therefore I try to scan pictures of DL (different states) from my PC's monitor. Could this be a reason?

**Comment by culoi** [comment]
Hi @epetrenko 

Sure, this is known as Moire pattern, an interference between camera and monitor frequencies: https://en.wikipedia.org/wiki/Moir%C3%A9_pattern

Also, samples are often small in size, the best is to scale them over the whole screen and then try to scan or find a larger sample of the USDL.

Just to confirm, did you select United States - Drivers license from the green Change Document button? 
You can also go to settings and turn off Scan both side option and then scan only back side of the USDL.

Regards

**Comment by epetrenko** [comment]
Yeah, I did. And I tried both variants. When I turned off scanning both sides, sample app recognizes front side only as image, without actual data:
![device-2018-06-05-145125](https://user-images.githubusercontent.com/2900931/40974462-4e10b712-68d0-11e8-95a3-359f0888d7b4.png)

**Comment by culoi** [comment]
Hello @epetrenko 

Did you try with the backside? 

Regards

**Comment by epetrenko** [comment]
@culoi I've just tried to scan both sides from monitor (scaled image sample to the whole screen), and this did the trick. Was able to get correct result from sample. Thanks!
